// _lib/shape-hash.mjs - P4 shape-hash pure helpers.
//
// This module is deliberately artifact-free. It turns supported exported
// object/interface type declarations into canonical structural records and
// sha256 hashes. A later P4 producer can walk files and write shape-index.json
// on top of these helpers.

import { createHash } from 'node:crypto';

import { parseOxcOrThrow } from './parse-oxc.mjs';
import { computeLineStarts, lineOf } from './line-offset.mjs';
import { normalizeCodeShape } from './extract-ts-escapes.mjs';

export const SHAPE_HASH_NORMALIZED_VERSION = 'shape-hash.normalized.v1';

const GENERATED_HEADER_PATTERNS = [
  /@generated\b/i,
  /<auto-generated\b/i,
  /\bauto-generated\b/i,
  /\bgenerated by\b/i,
  /\bthis file is generated\b/i,
];

const GENERATED_PATH_PATTERNS = [
  {
    re: /(?:^|\/)(?:__generated__|generated)\//,
    evidence: 'path:generated-directory',
  },
  {
    re: /(?:^|\/)routeTree\.gen\.(?:ts|tsx|js|jsx|mjs|cjs)$/,
    evidence: 'path:routeTree.gen',
  },
  {
    re: /\.(?:gen|generated)\.(?:d\.)?(?:ts|tsx|js|jsx|mjs|cjs)$/,
    evidence: 'path:generated-suffix',
  },
];

export function detectGeneratedFileEvidence(filePath, src = '') {
  const norm = String(filePath ?? '').replace(/\\/g, '/');
  for (const pattern of GENERATED_PATH_PATTERNS) {
    if (pattern.re.test(norm)) {
      return {
        kind: 'generated-file',
        source: 'path',
        evidence: pattern.evidence,
      };
    }
  }

  const header = String(src ?? '').slice(0, 2048);
  for (const re of GENERATED_HEADER_PATTERNS) {
    if (re.test(header)) {
      return {
        kind: 'generated-file',
        source: 'header',
        evidence: 'header:generated-marker',
      };
    }
  }

  return null;
}

function sourceSlice(src, node) {
  if (!node || typeof node.start !== 'number' || typeof node.end !== 'number') return '';
  return src.slice(node.start, node.end);
}

function compactTypePunctuation(input) {
  const out = [];
  let state = 'code';
  let i = 0;
  let skipSpaces = false;

  function trimTrailingSpace() {
    if (out[out.length - 1] === ' ') out.pop();
  }

  while (i < input.length) {
    const c = input[i];
    const next = input[i + 1];

    if (state === 'single') {
      out.push(c);
      if (c === '\\' && i + 1 < input.length) { out.push(next); i += 2; continue; }
      if (c === "'") state = 'code';
      i++;
      continue;
    }
    if (state === 'double') {
      out.push(c);
      if (c === '\\' && i + 1 < input.length) { out.push(next); i += 2; continue; }
      if (c === '"') state = 'code';
      i++;
      continue;
    }
    if (state === 'template') {
      out.push(c);
      if (c === '\\' && i + 1 < input.length) { out.push(next); i += 2; continue; }
      if (c === '`') state = 'code';
      i++;
      continue;
    }

    if (c === "'") { state = 'single'; out.push(c); skipSpaces = false; i++; continue; }
    if (c === '"') { state = 'double'; out.push(c); skipSpaces = false; i++; continue; }
    if (c === '`') { state = 'template'; out.push(c); skipSpaces = false; i++; continue; }

    if (/\s/.test(c)) {
      if (!skipSpaces && out[out.length - 1] !== ' ') out.push(' ');
      i++;
      continue;
    }

    if (/^[<>()\[\]{}|&:,;=?]$/.test(c)) {
      trimTrailingSpace();
      out.push(c);
      skipSpaces = true;
      i++;
      continue;
    }

    out.push(c);
    skipSpaces = false;
    i++;
  }

  return out.join('').trim();
}

export function normalizeTypeText(raw) {
  return compactTypePunctuation(normalizeCodeShape(raw));
}

function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (!value || typeof value !== 'object') return value;
  const out = {};
  for (const key of Object.keys(value).sort()) {
    out[key] = stableValue(value[key]);
  }
  return out;
}

function stableJson(value) {
  return JSON.stringify(stableValue(value));
}

function hashNormalizedShape(normalizedShape) {
  return 'sha256:' + createHash('sha256').update(stableJson(normalizedShape)).digest('hex');
}

function diag(code, message, extra = {}) {
  return {
    kind: 'shape-hash-diagnostic',
    code,
    severity: code === 'parse-error' ? 'error' : 'warning',
    message,
    ...extra,
  };
}

function memberName(member, src) {
  if (member?.computed) return null;
  const key = member?.key;
  if (!key) return null;
  if (key.type === 'Identifier' || key.type === 'PrivateIdentifier') return key.name;
  if (key.type === 'Literal' || key.type === 'StringLiteral' || key.type === 'NumericLiteral') {
    return String(key.value);
  }
  return sourceSlice(src, key).replace(/^['"]|['"]$/g, '');
}

function membersOfDeclaration(declaration) {
  if (declaration?.type === 'TSInterfaceDeclaration') {
    return declaration.body?.body ?? [];
  }
  if (
    declaration?.type === 'TSTypeAliasDeclaration' &&
    declaration.typeAnnotation?.type === 'TSTypeLiteral'
  ) {
    return declaration.typeAnnotation.members ?? [];
  }
  return null;
}

function normalizeLiteralUnionMember(typeNode, src, identity) {
  if (typeNode?.type === 'TSNullKeyword') return { ok: true, literal: { kind: 'null', value: null } };
  if (typeNode?.type === 'TSUndefinedKeyword') return { ok: true, literal: { kind: 'undefined', value: null } };
  if (typeNode?.type !== 'TSLiteralType') {
    return {
      ok: false,
      diagnostic: diag(
        'unsupported-literal-union-member',
        `unsupported literal union member: ${typeNode?.type ?? 'unknown'}`,
        { identity }
      ),
    };
  }

  const literal = typeNode.literal;
  if (literal?.type === 'Literal') {
    const value = literal.value;
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      return { ok: true, literal: { kind: typeof value, value } };
    }
    if (typeof value === 'bigint') {
      return { ok: true, literal: { kind: 'bigint', value: value.toString() } };
    }
  }

  if (literal?.type === 'TemplateLiteral' && literal.expressions?.length === 0 && literal.quasis?.length === 1) {
    const value = literal.quasis[0]?.value?.cooked ?? literal.quasis[0]?.value?.raw;
    if (typeof value === 'string') {
      return { ok: true, literal: { kind: 'string', value } };
    }
  }

  return {
    ok: false,
    diagnostic: diag(
      'unsupported-literal-union-member',
      `unsupported literal union member: ${sourceSlice(src, typeNode) || literal?.type || 'unknown'}`,
      { identity }
    ),
  };
}

function literalUnionMembersOfDeclaration(declaration) {
  if (declaration?.type !== 'TSTypeAliasDeclaration') return null;
  const annotation = declaration.typeAnnotation;
  if (!annotation) return null;
  if (annotation.type === 'TSUnionType') return annotation.types ?? [];
  if (
    annotation.type === 'TSLiteralType' ||
    annotation.type === 'TSNullKeyword' ||
    annotation.type === 'TSUndefinedKeyword'
  ) {
    return [annotation];
  }
  return null;
}

function normalizeLiteralUnionDeclaration(declaration, src, context = {}) {
  const identity = context.identity ?? null;
  const members = literalUnionMembersOfDeclaration(declaration);
  if (!members) return null;

  const diagnostics = [];
  const byKey = new Map();
  for (const member of members) {
    const normalized = normalizeLiteralUnionMember(member, src, identity);
    if (!normalized.ok) {
      diagnostics.push(normalized.diagnostic);
      continue;
    }
    byKey.set(stableJson(normalized.literal), normalized.literal);
  }

  if (diagnostics.length > 0) {
    return { ok: false, normalizedShape: null, fields: [], literals: [], diagnostics };
  }

  const literals = [...byKey.values()].sort((a, b) => {
    const aj = stableJson(a);
    const bj = stableJson(b);
    return aj < bj ? -1 : (aj > bj ? 1 : 0);
  });

  const normalizedShape = {
    schemaVersion: SHAPE_HASH_NORMALIZED_VERSION,
    shapeKind: 'literal-union',
    literals,
  };

  return { ok: true, normalizedShape, fields: [], literals, diagnostics: [] };
}

function normalizeShapeDeclaration(declaration, src, context = {}) {
  const identity = context.identity ?? null;
  const diagnostics = [];

  if (!declaration || typeof declaration !== 'object') {
    return {
      ok: false,
      normalizedShape: null,
      fields: [],
      diagnostics: [diag('missing-declaration', 'missing declaration node', { identity })],
    };
  }

  if (declaration.typeParameters?.params?.length > 0) {
    return {
      ok: false,
      normalizedShape: null,
      fields: [],
      diagnostics: [diag(
        'unsupported-type-parameters',
        'generic type declarations are deferred until checker-grade shape support',
        { identity }
      )],
    };
  }

  const literalUnion = normalizeLiteralUnionDeclaration(declaration, src, context);
  if (literalUnion) return literalUnion;

  const members = membersOfDeclaration(declaration);
  if (!members) {
    return {
      ok: false,
      normalizedShape: null,
      fields: [],
      diagnostics: [diag(
        'unsupported-declaration-shape',
        `unsupported declaration shape: ${declaration.type}`,
        { identity }
      )],
    };
  }

  const fields = [];
  for (const member of members) {
    if (member.type !== 'TSPropertySignature' && member.type !== 'TSMethodSignature') {
      diagnostics.push(diag(
        'unsupported-member-kind',
        `unsupported member kind: ${member.type}`,
        { identity }
      ));
      continue;
    }

    const name = memberName(member, src);
    if (!name) {
      diagnostics.push(diag('unsupported-member-key', 'unsupported or computed member key', { identity }));
      continue;
    }

    if (member.type === 'TSPropertySignature') {
      const typeNode = member.typeAnnotation?.typeAnnotation;
      if (!typeNode) {
        diagnostics.push(diag('missing-type-annotation', `missing type annotation for field ${name}`, { identity }));
        continue;
      }
      fields.push({
        kind: 'property',
        name,
        optional: !!member.optional,
        readonly: !!member.readonly,
        type: normalizeTypeText(sourceSlice(src, typeNode)),
      });
      continue;
    }

    fields.push({
      kind: 'method',
      name,
      optional: !!member.optional,
      readonly: false,
      type: `method${normalizeTypeText(src.slice(member.key.end, member.end))}`,
    });
  }

  if (diagnostics.length > 0) {
    return { ok: false, normalizedShape: null, fields: [], diagnostics };
  }

  fields.sort((a, b) => {
    if (a.name !== b.name) return a.name < b.name ? -1 : 1;
    if (a.kind !== b.kind) return a.kind < b.kind ? -1 : 1;
    return stableJson(a) < stableJson(b) ? -1 : (stableJson(a) > stableJson(b) ? 1 : 0);
  });

  const normalizedShape = {
    schemaVersion: SHAPE_HASH_NORMALIZED_VERSION,
    shapeKind: 'object',
    fields,
  };

  return { ok: true, normalizedShape, fields, diagnostics: [] };
}

function exportedAliases(program) {
  const aliases = new Map();
  function add(localName, exportedName) {
    if (!localName || !exportedName) return;
    if (!aliases.has(localName)) aliases.set(localName, new Set());
    aliases.get(localName).add(exportedName);
  }

  for (const stmt of program?.body ?? []) {
    if (stmt?.type !== 'ExportNamedDeclaration' || stmt.source || stmt.declaration) continue;
    for (const spec of stmt.specifiers ?? []) {
      if (spec?.type !== 'ExportSpecifier') continue;
      add(spec.local?.name, spec.exported?.name ?? spec.local?.name);
    }
  }
  return aliases;
}

function topLevelTypeDeclarations(program) {
  const out = [];
  const aliases = exportedAliases(program);

  for (const stmt of program?.body ?? []) {
    if (stmt?.type === 'ExportNamedDeclaration' && stmt.declaration) {
      const d = stmt.declaration;
      if (d.type === 'TSInterfaceDeclaration' || d.type === 'TSTypeAliasDeclaration') {
        const localName = d.id?.name;
        if (localName) out.push({ declaration: d, exportedName: localName });
      }
      continue;
    }

    if (stmt?.type === 'TSInterfaceDeclaration' || stmt?.type === 'TSTypeAliasDeclaration') {
      const localName = stmt.id?.name;
      const exportedNames = aliases.get(localName);
      if (!exportedNames) continue;
      for (const exportedName of exportedNames) {
        out.push({ declaration: stmt, exportedName });
      }
    }
  }

  return out;
}

function buildShapeHashFact({
  declaration,
  src,
  ownerFile,
  exportedName,
  line,
  source = 'fresh-ast-pass',
  scope = 'TS/JS production files, exported types only',
  observedAt = new Date().toISOString(),
}) {
  const identity = `${ownerFile}::${exportedName}`;
  const normalized = normalizeShapeDeclaration(declaration, src, { identity });
  if (!normalized.ok) {
    return {
      fact: null,
      diagnostics: normalized.diagnostics.map((d) => ({ ...d, ownerFile, exportedName, identity })),
    };
  }

  const hash = hashNormalizedShape(normalized.normalizedShape);
  const generatedFile = detectGeneratedFileEvidence(ownerFile, src);
  return {
    fact: {
      kind: 'shape-hash',
      hash,
      identities: [identity],
      identity,
      exportedName,
      ownerFile,
      typeKind: declaration.type,
      shapeKind: normalized.normalizedShape.shapeKind,
      line,
      fields: normalized.fields,
      ...(normalized.literals?.length ? { literals: normalized.literals } : {}),
      source,
      scope,
      confidence: 'high',
      observedAt,
      ...(generatedFile ? { generatedFile } : {}),
    },
    diagnostics: [],
  };
}

export function extractShapeHashFactsFromSource(src, filePath, options = {}) {
  const facts = [];
  const diagnostics = [];
  let parsed;
  try {
    parsed = parseOxcOrThrow(filePath, src);
  } catch (e) {
    return {
      facts,
      diagnostics: [diag('parse-error', e.message, { file: filePath })],
    };
  }

  const lineStarts = computeLineStarts(src);
  const entriesByIdentity = new Map();
  for (const entry of topLevelTypeDeclarations(parsed.program)) {
    const line = lineOf(lineStarts, entry.declaration.start ?? 0);
    const identity = `${filePath}::${entry.exportedName}`;
    if (!entriesByIdentity.has(identity)) entriesByIdentity.set(identity, []);
    entriesByIdentity.get(identity).push({ ...entry, line, identity });
  }

  for (const [identity, entries] of entriesByIdentity) {
    if (entries.length > 1) {
      diagnostics.push(diag(
        'declaration-merge-unsupported',
        'multiple exported type declarations share one identity; TS declaration merging is deferred',
        {
          file: filePath,
          identity,
          exportedName: entries[0].exportedName,
          declarations: entries.map((entry) => ({
            line: entry.line,
            type: entry.declaration.type,
          })),
        }
      ));
      continue;
    }

    const entry = entries[0];
    const { fact, diagnostics: factDiagnostics } = buildShapeHashFact({
      declaration: entry.declaration,
      src,
      ownerFile: filePath,
      exportedName: entry.exportedName,
      line: entry.line,
      source: options.source,
      scope: options.scope,
      observedAt: options.observedAt,
    });
    if (fact) facts.push(fact);
    diagnostics.push(...factDiagnostics);
  }

  return { facts, diagnostics };
}

export function groupShapeFactsByHash(facts) {
  const groups = {};
  for (const fact of facts ?? []) {
    if (!fact?.hash) continue;
    if (!groups[fact.hash]) groups[fact.hash] = [];
    groups[fact.hash].push(...(fact.identities ?? []));
  }
  for (const hash of Object.keys(groups)) {
    groups[hash].sort();
  }
  return groups;
}
