# VOC 목록 — DS Cloud / 가상 자원(Container)-DKS (2026-07-19 ~ 2026-07-25)

- **수집 기간**: 2026-07-19 ~ 2026-07-25
- **시스템/세부시스템**: DS Cloud > 가상 자원(Container)-DKS
- **전체 건수**: **16건**

---

## 요약 목록

| 번호 | VOC 번호 | 등록일시 | 문의자 / 부서 | 문의 유형 | 제목 / 핵심 내용 | 상태 |
|:---:|:---:|:---:|:---|:---:|:---|:---:|
| [1] | 2026072321353576302 | 2026-07-23 21:35:35 | 주영민 / 솔루션MSP그룹 | 사용법 문의 | pod 내부의 파일 가져오고 싶습니다 (DKS-N에서 Pod 파일 반출 시 DKSctl 및 사내 filerepo/Nexus 경유 방식 안내) | 처리완료 |
| [2] | 2026072317562275536 | 2026-07-23 17:56:22 | 안인성 / Solution개발팀 | 사용법 문의 | DKS 웹페이지 운영관리 네임스페이스관리 문의 (네임스페이스 관리 화면에서 request/limit 기준 리소스 노출 이상 확인 및 조치 예정 안내) | 처리완료 |
| [3] | 2026072316004973875 | 2026-07-23 16:00:49 | 정지민 / Flash YE팀 | 장애/오류 접수 | 프로젝트 검색이 안됩니다 (Cloud User Portal에서 생성한 임시과제 매핑 건: AA 매핑 및 Business Domain 등록 절차 안내) | 처리완료 |
| [4] | 2026072310450269734 | 2026-07-23 10:45:02 | 정효진 / 설비/인프라IT그룹 | 사용법 문의 | Knox API 시, IP 기입 & 방화벽 문의 (Pod의 대외 Knox API 통신 시 Node IP 대역을 방화벽 Source로 신청 안내) | 처리완료 |
| [5] | 2026072220402366315 | 2026-07-22 20:40:23 | 정재훈 / 설비/인프라IT그룹 | 사용법 문의 | SAS/Taylor DKS portal 문 (P-DEP 배포 파드 조회를 위한 SAS/Taylor 해외 리전 DKS 전담 담당자 안내) | 처리완료 |
| [6] | 2026072214531162988 | 2026-07-22 14:53:11 | 김정태 / 인프라AX/PI팀 | 수요/자원 문의 | DKS 수요 조사에서 산정근거 양식 작성 관련하여 문의드립니다 (수요조사 신청 시 서비스 분과 구조와 무관하게 사용 목적(운영/개발/STG) 단위 작성 안내) | 처리완료 |
| [7] | 2026072119525355656 | 2026-07-21 19:52:53 | 김철호 / 전자파트너 | 기타 | P-Dep Product의 deployment.yaml에서 liveness probe, readiness probe 설정 방법 문의 (deployment.yaml spec.template.spec.containers 내 프로브 정의 직접 추가 가이드) | 처리완료 |
| [8] | 2026072118561255426 | 2026-07-21 18:56:12 | 전희광 / DS IT그룹 | 사용법 문의 | StatefulSet으로 배포 시, Harbor Registry에 등록된 이미지 pull 단계에서 인증 관련 문의 (401 Unauthorized 원인인 Harbor pull secret 내 잘못된 인증 데이터 수정 및 조치) | 처리완료 |
| [9] | 2026072117571555072 | 2026-07-21 17:57:15 | 배동훈 / 비즈니스플랫폼1그룹 | 사용법 문의 | contour 버전 업그레이드 문의 (1.21+) (DKS-C는 Contour 1.33 및 Gateway API v1 지원 중이며 리다이렉트 등 기능 지원 안내) | 처리완료 |
| [10] | 2026072112175149967 | 2026-07-21 12:17:51 | 이준원 / 메모리미래FAB혁신그룹 | 기타 | PVC DB 활용 문제 (파드 내부 쓰기권한 확인 및 파일 업로드 시 filerepo/Nexus -> DKSctl -> k cp 경유 절차 안내) | 처리완료 |
| [11] | 2026072111103949120 | 2026-07-21 11:10:39 | 윤승현 / 설비/인프라IT그룹 | 사용법 문의 | Stateful set 배포 실패 trace요청 (Helm 배포 시 resourceVersion 충돌 필드 제거 및 Helm 기본 타임아웃 5분 연장/프로브 점검 안내) | 처리완료 |
| [12] | 2026072110501548680 | 2026-07-21 10:50:15 | 전용본 / 생산자동화IT그룹 | 방화벽/네트워크 문의 | prd-apps-pb01-khm -> MOS DB(NRD-K, NRD-P) 방화벽 문의 (DKS 클러스터별 Node IP 대역을 방화벽 Source로 신청 안내) | 처리완료 |
| [13] | 2026072018213244331 | 2026-07-20 18:21:32 | 윤창흠 / Generative AI팀 | 장애/오류 접수 | Ingress 에서 100mb 설정했는데 100mb 파일 업로드가 안되는거 같은데 확인 가능하실까요? (Nginx Ingress annotation 설정 정상이나 파드 애플리케이션 자체 이슈로 종결) | 처리완료 |
| [14] | 2026072016175342546 | 2026-07-20 16:17:53 | 윤창흠 / Generative AI팀 | 장애/오류 접수 | Knox 결재 취소 하였는데 사이트에서 취소가 안되고 있습니다 (녹스 결재 취소 오류 건으로 녹스 서비스데스크 이관 안내) | 처리완료 |
| [15] | 2026072015321041738 | 2026-07-20 15:32:10 | 김철호 / 전자파트너 | 사용법 문의 | kubectl oidc token 초기화 방법 가이드 요청 (DKS-C OIDC 이전 토큰 노출 현상에 대해 사용자 AD 재로그인 및 신규 계정 토큰 발급 지원) | 처리완료 |
| [16] | 2026072013464639912 | 2026-07-20 13:46:46 | 이재환 / 생산자동화IT그룹 | 사용법 문의 | DKS 웹콘솔 외 다른 접근 방법 문의 (DKS-N은 DKSctl 및 웹 콘솔만 지원, 외부 kubectl 통신은 DKS-C 엔드포인트 제공 안내) | 처리완료 |

---

## [1] pod 내부의 파일 가져오고 싶습니다.

- **VOC 번호**: 2026072321353576302
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-23 21:35:35

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**주영민(ymin84.joo)/솔루션MSP그룹(솔루션운영)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: 메모리 제품 테스트 플랫폼
> - Cluster명: prod-ds-member
> - Namespace명: testplatform-prod
> 안녕하세요. pod 내부에 있는 file을 가져오고 싶은데요.
> 어떻게 진행하면 될까요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-24 10:54:47
> 안녕하세요. DKS 운영팀 입니다.
> DKS-N의 경우 따로 filerepo가 필요합니다.
> 예를들어 nexus(http://nexus.adpaas.cloud.samsungds.net)를 사용하신다면
> DKSctl 내부에서
> kubectl "네임스페이스/파드:경로" "DKSctl 경로" -c 컨테이너
> 명령을 통해 Pod -> DKSctl로 file을 가져오신 후
> curl -k -v -u '아이디:패스워드' -T 'DKSctl 경로' 'http://nexus.adpaas.cloud.samsungds.net/repository/레포명/파일 경로'
> 명령을 통해 DKSctl -> filerepo 로 옮기시면 됩니다.
> Pod -> DKSctl -> filerepo
> 감사합니다.

---

## [2] DKS 웹페이지 운영관리 네임스페이스관리 문의

- **VOC 번호**: 2026072317562275536
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-23 17:56:22

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**안인성(insng.ahn)/Solution개발팀(메모리)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: canvas
> - Cluster명: prd-apps-pb01-khm
> - Namespace명:
> 안녕하세요, Solution개발팀 안인성입니다.
> DKS 웹페이지 운영관리 네임스페이스관리에서
> request 기준으로 리소스가 나오는 경우가 있고 limit 기준으로 리소스가 나오는 경우가 있습니다.
> canvas-trino-prod: requests.cpu: 15/19, requests.memory: 132Gi/134Gi, limits.cpu: 15/57, limits.memory: 132Gi/402Gi
> canvas-spark-prod: requests.cpu: 30/30, requests.memory: 293Gi/300Gi, limits.cpu: 30/90, limits.memory: 293Gi/900Gi
> 감사합니다
> 안인성 드림

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-24 18:04:46
> 안녕하세요. DKS 운영팀 입니다.
> 해당 내용 확인 되어 추후 조치 예정 입니다.
> 사용자분에게 양해 부탁드리며
> 조치 후에 회신드리도록 하겠습니다.
> 감사합니다.

---

## [3] 프로젝트 검색이 안됩니다.

- **VOC 번호**: 2026072316004973875
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-07-23 16:00:49

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**정지민(junjin.chung)/Flash YE팀(글로벌 제조&인프라총괄)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: Geometry기반-공정Window-분석시스템
> - Cluster명: -
> - Namespace명: -
> cloud user portal 프로젝트 등록에서 아래와 같 프로젝트 생성하였으나, DKS에서 프로젝트 조회가 되지 않습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-24 10:35:07
> 안녕하세요. DKS 운영팀 입니다.
> 해당 프로젝트가 현재 임시 과제라고 합니다.
> 수요 시스템 관련 문의로 이관드리며
> 문의자분이 다음주 부재여서
> 다음 주 연락이 필요하실 경우 나유식 님에게 연락주시면 된다고 합니다.
> 감사합니다.

**임정원(callist.lim)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-07-27 09:35:52
> 프로젝트 검색이 안되는 경우는 임시과제가 매핑되어있는 경우입니다.
> AA를 매핑하시면 검색이되며
> Bussiness Domain을 등록하셔야 프로젝트 선택이 가능합니다.

---

## [4] Knox API 시, IP 기입 & 방화벽 문의

- **VOC 번호**: 2026072310450269734
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-23 10:45:02

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**정효진(hjin99.jeong)/설비/인프라IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: yms-error-analyzer-dev / yms-error-analyzer-prod
> - Cluster명: dev-apps-pb01-khs / prd-apps-pb01-khm
> - Namespace명: yms-batch-dev / yms-batch-prod
> 위 project에서 cronjob으로 Knox API의 개발/운영 계정을 연결할 계획입니다.
> 현재 Knox API를 신청할 때, 해당 API를 사용하는 곳의 IP를 신청해야 하는데 이렇게 POD에서 API가 돌아갈 때는
> IP를 뭐라고 신청해야 하는지 궁금합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-23 11:23:20
> 안녕하세요. DKS 운영팀 입니다.
> DKS 내부에서 DKS 외부로 통신하실 때는
> Node의 IP를 가지고 나가기 때문에 Node IP로 신청해주시면 될 것 같은데요.
> 저희가 Node IP 대역을 아래 링크에서 안내드리고 있습니다.
> DKS Pod -> 외부 시스템로의 통신이 필요합니다 - DS Wikipedia - DS Confluence
> Node IP 대역으로 신청 가능하신지 한번 확인해보시면 될 것 같습니다.
> 감사합니다.

---

## [5] SAS/Taylor DKS portal 문

- **VOC 번호**: 2026072220402366315
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-22 20:40:23

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**정재훈(jaeh00n.jung)/설비/인프라IT그룹(AX/PI센터)**
> 안녕하세요
> P-DEP 을 통해 SAS/Taylor에 배포중입니다만
> DKS에서 해당 Pod를 보려면 어떻게 해야 할까요?
> prd-apps-pa01-tas
> yms-app-prd
> us-flops-portal--flops-backend-prod-66c7fffd95-hrcb9
> dks.samsungds.net 외에 링크가 있다면 가이드 부탁드립니다.
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: SSQS
> - Cluster명:
> - Namespace명:

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-23 11:10:29
> 안녕하세요. DKS 운영팀 입니다.
> DKS SAS/Talyer 관련 문의는 아래 담당자 분을 통해 문의 바랍니다.
> - Venkata Ramana Dupakuntla
> - Sasikumar Vilvapathy
> 감사합니다.

---

## [6] DKS 수요 조사에서 산정근거 양식 작성 관련하여 문의드립니다.

- **VOC 번호**: 2026072214531162988
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-07-22 14:53:11

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김정태(jt0612.kim)/인프라AX/PI팀(글로벌 제조&인프라총괄)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에
> Project명,
> Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: 글앤총LLM전처리서버
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: gmitapi-prod
> 안녕하세요.
> DKS 수요조사 중 산정근거 양식 작성 관련하여 문의드립니다.
> DKS 자원산정 근거를 작성할 때 서비스별로 작성해야 할 것으로 보입니다.
> 저희 Project는 Agent가 많고, 같은 이름의 Agent도 분과별로 나눠져 있어 어떤 단위로 묶어 한 서비스(한 Row)로 나타내야 할 지 어렵습니다.
> 제가 생각했을 때는 다음 중 하나일 것으로 보입니다.
> 1. 사용 목적으로 나눠 작성합니다. (운영 - 모든 Agent, 개발 - 모든 Agent, 스테이징 - 모든 Agent)
> 2. 작은 서비스 단위로 Backend, Frontend를 묶어 작성합니다. (A Agent A 분과 FE & BE, A Agent B 분과 FE & BE)
> 3. 목적에 맞게 서비스를 묶어 작성합니다. (A Agent FE & BE, B Agent FE & BE)
> 물론 분과마다 P-DEP 기준으로 Product가 나뉘어져 있긴 합니다.
> 이러한 구조에 대해 의견 주시면 감사하겠습니다.

**서지희(jwlgmlz.seo)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-07-22 16:05:45
> 안녕하세요.
> 수요조사 신청 시 운영/개발/스테이징을 선택하게 되어 있어,
> 말씀하신 1번으로 진행해주시면 되겠습니다.
> "1. 사용 목적으로 나눠 작성합니다. (운영 - 모든 Agent, 개발 - 모든 Agent, 스테이징 - 모든 Agent)"
> 감사합니다.

---

## [7] P-Dep Product의 deployment.yaml에서 liveness probe, readiness probe 설정 방법 문의

- **VOC 번호**: 2026072119525355656
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-07-21 19:52:53

### 대화 내용

> *(이관/중계성 안내 메시지 3건 제거)*

**김철호(chulhop.kim)/전자파트너**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> AA Module Name : https://devops.samsungds.net/?systemid=people360@serviceid=
> Product Group ID or Name : people360
> Product ID or Name : p360-home-knox-agent-dev
> 안녕하세요.
> P360 홈위젯/CCC ITO 김철호 입니다.
> P-Dep으로 생성한 Deploymeny.yaml에는 liveness probe, readiness probe 가 없는 것으로 보여지는데요.
> P-Dep에서 설정하는 방법에 대해 문의드립니다.
> 감사합니다.

**홍종일(jongil2.hong)/PLM실행그룹(디지털PLM)** · [게시됨] · 등록일: 2026-07-22 11:32:36
> 안녕하세요. P-DEP 담당자 입니다.
> deployment.yaml의 container 정의 항목(spec.template.spec.containers)에 아래의 예처럼 직접 수정하여 추가시면 됩니다.
> ```yaml
> livenessProbe:
>   httpGet:
>     path: "{사용하실 Health Check URL}"
>     port: 8080
>     scheme: "HTTP"
>   initialDelaySeconds: 30
>   timeoutSeconds: 3
>   periodSeconds: 10
>   successThreshold: 1
>   failureThreshold: 9
> readinessProbe:
>   httpGet:
>     path: "{사용하실 Health Check URL}"
>     port: 8080
>     scheme: "HTTP"
>   initialDelaySeconds: 20
>   timeoutSeconds: 3
>   periodSeconds: 10
>   successThreshold: 1
>   failureThreshold: 6
> ```
> 추가 문의 내용이 있으시면 재문의 바랍니다.
> 고맙습니다.

---

## [8] StatefulSet으로 배포 시, Harbor Registry에 등록된 이미지 pull 단계에서 인증 관련 문의

- **VOC 번호**: 2026072118561255426
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-21 18:56:12

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**전희광(heekwang.jeon)/DS IT그룹(전자/제조IT)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: Digital-HR-Platform
> - Cluster명: peoplein360-dev
> - Namespace명: people-in-360
> KMS Agent 서비스를 StatefulSet으로 띄우려고 하는데
> Harbor Registry에 등록한 이미지 pull이 제대로 안되고 있습니다.
> 아래와 같이 secret도 생성하여 연결을 해봤으나 인증이 안되는 것 같은데 다른 방법이 있는지 문의드립니다.
> ※ Secret : harbor-secret
> https://console.dks.samsungds.net/4772/clusters/peoplein360-dev/secrets/people-in-360/harbor-secret
> ※ Harbor Registry 주소
> harbor.dks.samsungds.net/dks-registry-4772/secure-db-agent:V3.7.3-2.0.10
> ※ StatefulSet : sdb-agent
> https://console.dks.samsungds.net/4772/clusters/peoplein360-dev/statefulsets/people-in-360/sdb-agent
> Back-off pulling image "harbor.dks.samsungds.net/dks-registry-4772/secure-db-agent:V3.7.3-2.0.10": ErrImagePull: failed to pull and unpack image "harbor.dks.samsungds.net/dks-registry-4772/secure-db-agent:V3.7.3-2.0.10": failed to resolve reference "harbor.dks.samsungds.net/dks-registry-4772/secure-db-agent:V3.7.3-2.0.10": unexpected status from HEAD request to https://harbor.dks.samsungds.net/v2/dks-registry-4772/secure-db-agent/manifests/V3.7.3-2.0.10: 401 Unauthorized

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-22 15:37:13
> 안녕하세요. DKS 운영팀 입니다.
> 확인 결과 secret의 데이터에 잘못된 값이 들어간 것으로 보입니다.
> secret 수정 후 정상 확인 되었습니다.
> 감사합니다.

---

## [9] contour 버전 업그레이드 문의 (1.21+)

- **VOC 번호**: 2026072117571555072
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-21 17:57:15

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**배동훈(dsdb14882.id)/비즈니스플랫폼1그룹(DS)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: DS커리어컨설팅센터
> - Cluster명: dsportal-dev
> - Namespace명: ccc-1-dev
> 안녕하세요.
> 현재, ingress controller, gateway 에서 기본적으로 설치 제공해주신 contour 로 진행중에 있습니다.
> 현재 설치된 contour 의 경우 1.19 버전 이하라 아래의 기능을 진행하기 어려움에 있습니다.
>
> | 기능 | 1.19 이하 | 1.21+ |
> |---|:---:|:---:|
> | filters | ❌ | ✅ |
> | policy | ❌ | ✅ |
> | sizeLimit | ❌ | ✅ |
> | RequestRedirect | ❌ | ✅ |
> | ResponseHeaderModifier | ❌ | ✅ |
> | Gateway API v1 | ❌ | ✅ |
>
> kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
> https://raw.githubusercontent.com/projectcontour/contour/release-1.33/examples/render/contour.yaml
> contour 의 업그레이드와 관련해서 설치 또는 가이드 지원 요청 드립니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-22 16:07:48
> 안녕하세요. DKS 운영팀 입니다.
> DKS-C 에서는 현재 contour 1.33 버전을 사용 중이며
> RequestRedirect, ResponseHeaderModifier, Gateway API v1 은 모두 지원 됩니다.
> 위에 언급한 기능에 관련해서 아래 링크에 가이드가 작성되어 있습니다.
> Gateway 구성 - DS Wikipedia - DS Confluence
> 다만, 말씀하신 filters, policy, sizeLimit 의 경우 어떤 기능에 대해 문의 주신 것인지 알기 어려워서 혹시 사용하신 manifest 나 관련 레퍼런스, 예제 등을 첨부하여 재문의 주시거나 dksmgmt.sec@samsung.com 계정에 메일을 통해 보내주시면 확인 해보겠습니다.
> 감사합니다.

---

## [10] PVC DB 활용 문제

- **VOC 번호**: 2026072112175149967
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-07-21 12:17:51

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**이준원(junwon99.lee)/메모리미래FAB혁신그룹(글로벌 제조&인프라총괄)**
> 하기와 같이 PVC 내에 적재한 DB를 Prod가 제대로 가져오지 못하여 서비스가 안되는 문제가 있습니다.
> pod에 root 접근하여 /app/storage를 들여다보면 원하는 db가 잘 올라가있는 것을 알 수 있는데,
> 실행하면 DB를 불러올 수 없다는 문제가 발생합니다.
> Writing 권한이 없어 그런것인가요?
> 그리고 kubectl 전송을 위한 config에 접근 권한이 없어 harbor와 같은 artifact에 db를 image와 하여 pull 하고 임시 포드에서 pvc로 복사하는 방식을 활용하였는데
> 이게 최선의 방법일까요? 너무 번거로운 작업이어서 어떻게 pvc 내에 db를 옮기는 것이 정석인지 궁금합니다
> ```
> d] $ kubectl exec -it data-wiki--voda7-prod-74fbb54765-t6bx6 -n mtcedu-prod -- /bin/bash
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# find /app -name "voda.db"
> /app/storage/voda.db
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# env | grep -E "STORAGE|DATA|RUNTIME|JOURNAL"
> DATA_WIKI__VODA3_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA5_PROD_SVC_SERVICE_PORT_HTTP=80
> DATA_WIKI__VODA2_PROD_SVC_PORT_80_TCP=tcp://10.223.249.145:80
> DATA_WIKI__VODA4_PROD_SVC_SERVICE_PORT_HTTP=80
> DATA_WIKI__VODA6_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA6_PROD_SVC_PORT_80_TCP_PORT=80
> DATA_WIKI__VODA7_PROD_SVC_PORT=tcp://10.223.245.98:80
> DATA_WIKI__VODA6_PROD_SVC_SERVICE_PORT_HTTP=80
> DATA_WIKI__VODA4_PROD_SVC_PORT_80_TCP_ADDR=10.223.154.97
> DATA_WIKI__VODA5_PROD_SVC_SERVICE_HOST=10.223.230.52
> DATA_WIKI__VODA7_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA2_PROD_SVC_PORT_80_TCP_PORT=80
> DATA_WIKI__VODA3_PROD_SVC_PORT_80_TCP_PORT=80
> DATA_WIKI__VODA7_PROD_SVC_PORT_80_TCP=tcp://10.223.245.98:80
> DATA_WIKI__VODA7_PROD_SVC_PORT_80_TCP_PORT=80
> VODA_STORAGE_DIR=/app/storage
> DATA_WIKI__VODA7_PROD_SVC_SERVICE_PORT=80
> DATA_WIKI__VODA6_PROD_SVC_PORT=tcp://10.223.255.229:80
> DATA_WIKI__VODA5_PROD_SVC_PORT_80_TCP=tcp://10.223.230.52:80
> DATA_WIKI__VODA2_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA5_PROD_SVC_SERVICE_PORT=80
> VODA_SQLITE_JOURNAL_MODE=DELETE
> DATA_WIKI__VODA4_PROD_SVC_PORT=tcp://10.223.154.97:80
> DATA_WIKI__VODA6_PROD_SVC_PORT_80_TCP_ADDR=10.223.255.229
> DATA_WIKI__VODA3_PROD_SVC_SERVICE_PORT=80
> DATA_WIKI__VODA3_PROD_SVC_SERVICE_HOST=10.223.192.51
> DATA_WIKI__VODA4_PROD_SVC_SERVICE_HOST=10.223.154.97
> DATA_WIKI__VODA4_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA7_PROD_SVC_PORT_80_TCP_ADDR=10.223.245.98
> DATA_WIKI__VODA5_PROD_SVC_PORT_80_TCP_PROTO=tcp
> DATA_WIKI__VODA3_PROD_SVC_PORT_80_TCP_ADDR=10.223.192.51
> TABLE_AGENT_DATA_DIR=/app/storage
> DATA_WIKI__VODA4_PROD_SVC_SERVICE_PORT=80
> DATA_WIKI__VODA5_PROD_SVC_PORT_80_TCP_PORT=80
> VODA_RUNTIME_DIR=/tmp/voda-runtime
> DATA_WIKI__VODA6_PROD_SVC_PORT_80_TCP=tcp://10.223.255.229:80
> DATA_WIKI__VODA3_PROD_SVC_PORT=tcp://10.223.192.51:80
> DATA_WIKI__VODA4_PROD_SVC_PORT=tcp://10.223.154.97:80
> DATA_WIKI__VODA6_PROD_SVC_SERVICE_HOST=10.223.255.229
> DATA_WIKI__VODA2_PROD_SVC_SERVICE_PORT=80
> DATA_WIKI__VODA4_PROD_SVC_PORT_80_TCP_PORT=80
> DATA_WIKI__VODA2_PROD_SVC_PORT_80_TCP_ADDR=10.223.249.145
> DATA_WIKI__VODA7_PROD_SVC_SERVICE_HOST=10.223.245.98
> DATA_WIKI__VODA2_PROD_SVC_SERVICE_HOST=10.223.249.145
> DATA_WIKI__VODA5_PROD_SVC_PORT=tcp://10.223.230.52:80
> DATA_WIKI__VODA2_PROD_SVC_PORT=tcp://10.223.249.145:80
> DATA_WIKI__VODA3_PROD_SVC_PORT_80_TCP=tcp://10.223.192.51:80
> DATA_WIKI__VODA6_PROD_SVC_SERVICE_PORT=80
> DATA_WIKI__VODA3_PROD_SVC_PORT_80_TCP_HTTP=80
> DATA_WIKI__VODA5_PROD_SVC_PORT_80_TCP_ADDR=10.223.230.52
> DATA_WIKI__VODA7_PROD_SVC_SERVICE_PORT_HTTP=80
> DATA_WIKI__VODA2_PROD_SVC_SERVICE_PORT_HTTP=80
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# ls -ld /app/storage
> drwxrwxrwx 2 root root 4096 Jul 21 02:31 /app/storage
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# ls -ld /tmp/voda-runtime
> drwxrwxrwx 1 root root 27 Jul 21 03:01 /tmp/voda-runtime
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# ls -lh /app/storage
> total 3.2G
> -rwxrwxrwx 1 root root 3.2G Jul 21 02:31 voda.db
> -rw-r--r-- 1 root root 4.4M Jul 20 03:55 voda_focus_fast_cache_v2.json
> -rwxrwxrwx 1 root root 1.4M Jul 20 02:24 voda_usage_log.db
> -rw-r--r-- 1 root root 7.7M Jul 20 04:01 voda_visual_cache_v2.json
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# ls -la /app/storage | grep -E "shm|wal"
> root@data-wiki--voda7-prod-74fbb54765-t6bx6:/app# exit
> exit
> command terminated with exit code 1
> exit status 1
> 2026-07-21 03:04:29.737739814 +0000 UTC m=+62.661396998 write error: invalid argument
> [prd-apps-pb01-khm:mtcedu-prod] $ kubectl logs -f data-wiki--voda7-prod-74fbb54765-t6bx6 -n mtcedu-prod
> INFO: Waiting for application startup.
> 2026-07-21 03:04:32.612059952 +0000 UTC m=+0.068538609 write error: invalid argument
> INFO: Application startup complete.
> INFO: Uvicorn running on http://0.0.0.0:42761 (Press CTRL+C to quit)
> [VODA] automatic info-wiki generation is disabled (VODA_AUTO_FILL_INFO_WIKI=0)
> [VODA storage] db=/app/storage/voda.db source=direct:/app/storage writable=True journal=delete tables=11352 size=3386413056
> INFO: 192.223.100.12:52940 - "GET / HTTP/1.1" 200 OK
> INFO: 192.223.100.12:52940 - "POST /api/voda/action-log HTTP/1.1" 200 OK
> INFO: 192.223.137.137:36706 - "GET /api/voda/status HTTP/1.1" 200 OK
> ^C
> [prd-apps-pb01-khm:mtcedu-prod] $ kubectl logs -f data-wiki--voda7-prod-74fbb54765-t6bx6 -n mtcedu-prod
> 2026-07-21 03:05:20.572454829 +0000 UTC m=+0.074594779 write error: invalid argument
> INFO: Waiting for application startup.
> INFO: Application startup complete.
> INFO: Uvicorn running on http://0.0.0.0:42761 (Press CTRL+C to quit)
> [VODA] automatic info-wiki generation is disabled (VODA_AUTO_FILL_INFO_WIKI=0)
> [VODA storage] db=/app/storage/voda.db source=direct:/app/storage writable=True journal=delete tables=11352 size=3386413056
> INFO: 192.223.100.12:52940 - "GET / HTTP/1.1" 200 OK
> INFO: 192.223.100.12:52940 - "POST /api/voda/action-log HTTP/1.1" 200 OK
> INFO: 192.223.137.137:36706 - "GET /api/voda/status HTTP/1.1" 200 OK
> INFO: 192.223.210.11:51922 - "GET / HTTP/1.1" 200 OK
> INFO: 192.223.210.11:51922 - "POST /api/voda/action-log HTTP/1.1" 200 OK
> INFO: 192.223.137.137:50446 - "GET /api/voda/status HTTP/1.1" 200 OK
> ```

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-21 16:52:46
> 안녕하세요. DKS 운영팀 입니다.
> 우선 container 내부에서 root 이신 것, 파일에 쓰기 권한이 있는 것은 확인이 됩니다.
> pod 내부 문제로 보여서 더 지원드리기 어려운 점 양해 바랍니다.
> container 내부에 파일을 업로드 하는 것은 바로는 어려우며
> 예를들어 nexus 를 사용하신다면 DKSctl 내부에서
> `wget http://nexus.adpaas.cloud.samsungds.net/repository/repo/test`
> 와 같이 파일을 다운로드 받으시고
> `k cp "test" "mtcedu-prod/data-wiki--voda7-prod-b7f7b48f5-mvls4:/app/storage/test"` 와 같이 파일을 올리셔서
> filerepo -> DKSctl -> Container 로 옮기셔야 될 것 같습니다.
> 감사합니다.

---

## [11] Stateful set 배포 실패 trace요청

- **VOC 번호**: 2026072111103949120
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-21 11:10:39

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: YMS-Batch-ETL
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: yms-batch-prod
> Statefulset
> com-ssqs--mq-rabbit-prod-rabbitmq
> 위의 statefulset을 pdep을 통해 helm으로 배포 했습니다.
> 10시15분경 배포를 시작했고, 0,1,2가 Pod가 롤링 됐다가, 다시 rollback이 되었는데요.
> 혹시 어떤 이유로 롤백이됐는지 알 수 있을까요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-21 11:47:15
> 안녕하세요. DKS 운영팀 입니다.
> 확인 결과
> Jul 21, 2026 @ 10:14:45.120 로그에서
> `Operation cannot be fulfilled on statefulsets.apps "com-ssqs--mq-rabbit-prod-rabbitmq": the object has been modified; please apply your changes to the latest version and try again`
> 메시지가 확인 되었습니다.
> com-ssqs--mq-rabbit-prod-rabbitmq 수정하실 때 혹시 resourceVersion 필드가 있다면 해당 필드를 지우고 재배포 시도해주시기 바랍니다.
> 감사합니다.

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-07-21 15:42:17
> `helm history com-ssqs--mq-rabbit-prod -n yms-batch-prod` 명령으로 별도로 추가 로그를 확인했을 때
> 6 Tue Jul 21 10:12:25 2026 failed Upgrade failed: context deadline exceeded
> 7 Tue Jul 21 10:19:27 2026 failed Release failed: context deadline exceeded
> 이런 이력이 보이는데요, 혹시, helm의 배포기본 dead line이 있나요? 있다면 몇분인지 알려주시면 감사하겠습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-21 17:23:11
> 안녕하세요. DKS 운영팀 입니다.
> helm 의 --timeout 옵션의 설명에 의하면 default 5m0s 이라고 합니다.
> context deadline exceeded 이 문제였다고 한다면 10:15 ~ 10:20 사이에 있었던 Readiness probe failed 등이 연관되었을 수도 있을 것 같습니다.
> probe 관련하여 파드 내부 동작을 살펴보시거나 helm의 --timeout 옵션을 5분 이상으로 늘려서 확인해보셔야 할 것 같습니다.
> 감사합니다.

---

## [12] prd-apps-pb01-khm -> MOS DB(NRD-K, NRD-P) 방화벽 문의

- **VOC 번호**: 2026072110501548680
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-07-21 10:50:15

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**전용본(ynotbon.jeon)/생산자동화IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 사전 작업 - DS Wikipedia - DS Confluence
> (DKS콘솔) Ingress 배포 - DS Wikipedia - DS Confluence
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 문의 내용에
> Project명,
> Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: 제조WP
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: wp-auth-prod
> 안녕하세요, 생산자동화IT그룹 전용본입니다.
> prd-apps-pb01-khm 클러스터에서 MOS DB, 생산통합 DB 방화벽이 오픈되어 있는 것으로 아는데 NRD-K, NRD-P는 닫혀있는 듯 해서 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-21 11:34:23
> 안녕하세요. DKS 운영팀 입니다.
> DKS 내부에서 DKS 외부로 통신하실 때는
> DKS Cluster 별 Node의 IP 대역을 source로 방화벽이 Open 되어 있어야 합니다.
> 아래 링크를 참고해주시기 바랍니다.
> DKS Pod -> 외부 시스템로의 통신이 필요합니다 - DS Wikipedia - DS Confluence
> 감사합니다.

---

## [13] Ingress 에서 100mb 설정했는데 100mb 파일 업로드가 안되는거 같은데 확인 가능하실까요?

- **VOC 번호**: 2026072018213244331
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-07-20 18:21:32

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**윤창흠(chhm.yoon)/Generative AI팀(AX/PI센터)**
> Project : DSGuardrails
> Cluster : prod-ds-member
> Namespace : dsguardrails-prd
> Ingress : whisperx-prd-ingress
> Ingress 에서 100mb 설정했는데 100mb 파일 업로드가 안되는거 같은데 확인 가능하실까요?
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     nginx.ingress.kubernetes.io/proxy-body-size: 100m
> ```

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-21 14:08:41
> 안녕하세요. DKS 운영팀 입니다.
> 사용자 pod 내부 문제로 확인 되었습니다.
> 사용자 요청으로 voc 종료하겠습니다.
> 감사합니다.

---

## [14] Knox 결재 취소 하였는데 사이트에서 취소가 안되고 있습니다.

- **VOC 번호**: 2026072016175342546
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-07-20 16:17:53

### 대화 내용

**윤창흠(chhm.yoon)/Generative AI팀(AX/PI센터)**
> 신청번호 20260720-1728
> Knox 결재 취소 하였는데 사이트에서 취소가 안되고 있습니다.

**DS Cloud 서비스데스크2(dscsv2.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-07-20 16:20:14
> 접수 되었습니다.

**DS Cloud 서비스데스크2(dscsv2.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-07-20 16:20:14
> 접수 되었습니다.

**DS Cloud 서비스데스크2(dscsv2.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-07-20 16:21:05
> 안녕하세요 클라우드 상황실 입니다.
> knox 문의는 아래 녹스서비스데스크에 문의 부탁드립니다.
> knoxportal@samsung.com +82-2-1661-3311 > 2 > 3 > 2
> 감사합니다.
> ※ 추가적으로 궁금하신 내용에 대한 자세한 정보는
> https://confluence.samsungds.net/pages/viewpage.action?pageId=591849109 에서 검색 가능합니다.

---

## [15] kubectl oidc token 초기화 방법 가이드 요청

- **VOC 번호**: 2026072015321041738
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-20 15:32:10

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김철호(chulhop.kim)/전자파트너**
> 안녕하세요.
> P360 홈위젯/CCC ITO 김철호 입니다.
> DKS-C 접속용 장기 token을 발급받기 위해
> `kubectl oidc-login get-token --oidc-issuer-url=https://keycloak.dks.samsungds.net/realms/DKS --oidc-client-id=kube-login --oidc-use-access-token`
> 명령어를 실행했는데요.
> 비실명 AD 계정의 token 정보를 발급받으려하나 계속 이전 token 정보가 노출됩니다.
> 발급받은 token을 초기화하는 방법에 대해 가이드 부탁드립니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-20 15:50:22
> 안녕하세요. DKS 운영팀 입니다.
> 원격 지원 통하여 사용자 AD 재 로그인 및 digitalhr1.sec 계정으로 토큰 발급 확인 되었습니다.
> 감사합니다.

---

## [16] DKS 웹콘솔 외 다른 접근 방법 문의

- **VOC 번호**: 2026072013464639912
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-07-20 13:46:46

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**이재환(jam.lee)/생산자동화IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명:
> - Cluster명: dev-apps-pb01-khs, prd-apps-pb01-khm
> - Namespace명: wp-auth-dev, wp-auth-prod
> DKS 내 로그를 확인하거나 웹콘솔상에서 여러 명령어를 수행하는데,
> 혹시 웹콘솔 말고 다른 방식으로 ssh라던가 하는 방식으로 접근을하도록 하려면 어떻게해야할 지 알수 있을까요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-07-20 14:59:16
> 안녕하세요. DKS 운영팀 입니다.
> DKS-N 에서는 현재 DKSctl 과 웹 콘솔을 통한 접근 방법만 제공하고 있습니다.
> 더 많은 권한과 기능이 필요하시다면
> DKS-C에서는 외부에서 kube-apiserver와 통신 가능한 endpoint를 제공하고 있으니 참고하셔도 좋을 것 같습니다.
> (DKS-C 콘솔) 운영 가이드 - DS Wikipedia - DS Confluence
> 사전준비 - DS Wikipedia - DS Confluence
> 감사합니다.
