# VOC 목록 — DS Cloud / 가상 자원(Container)-DKS (2026-03-08 ~ 2026-03-14)

- **수집 기간**: 2026-03-08 ~ 2026-03-14
- **시스템/세부시스템**: DS Cloud > 가상 자원(Container)-DKS
- **전체 건수**: **11건**

---

## 요약 목록

| 번호 | VOC 번호 | 등록일시 | 문의자 / 부서 | 문의 유형 | 제목 / 핵심 내용 | 상태 |
|:---:|:---:|:---:|:---|:---:|:---|:---:|
| [1] | 2026031310191224424 | 2026-03-13 10:19:12 | 한주형 / Sensor PA팀 | 방화벽/네트워크 문의 | P-DEP FTP 통신 위한 DKS 방화벽 해제 IP 주소 관련 문의 (prd 클러스터 Outbound Source IP 대역 안내) | 처리완료 |
| [2] | 2026031307400622363 | 2026-03-13 07:40:06 | 김용수 / 설비/인프라IT그룹 | 방화벽/네트워크 문의 | DKS IP 대역 문의 (prd-apps-pb01-khm 클러스터에서 사내 DB 접근용 Source IP 대역 안내) | 처리완료 |
| [3] | 2026031213192417165 | 2026-03-12 13:19:24 | 이재민 / MTC AX/PI팀 | 수요/자원 문의 | DKS 자원의 OS 버전과 Kubernetes 버전 문의 (RHEL 8.6 및 K8s v1.26 표준 정책 안내) | 처리완료 |
| [4] | 2026031118270611712 | 2026-03-11 18:27:06 | 윤승현 / 설비/인프라IT그룹 | 사용법 문의 | ingress통한 접속시 bad gateway 에러 (Liveness Probe 실패로 인한 파드 비정상 연결 원인 규명 및 조치 안내) | 처리완료 |
| [5] | 2026031118241311694 | 2026-03-11 18:24:13 | 이강길 / Data Platform그룹 | 장애/오류 접수 | PDEP 정상 배포 이후 사이트 접속시 404 및 무한Redirect 오류 (Ingress 로그상 백엔드 Pod의 404 응답 확인 안내) | 처리완료 |
| [6] | 2026031112004206492 | 2026-03-11 12:00:42 | 전희광 / DS IT그룹 | 사용법 문의 | 웹콘솔 권한 확인 (DKSctl 웹콘솔 권한 내부 버그 확인, 3/23 패치 일정 및 콘솔 UI 대체 이용 안내) | 처리완료 |
| [7] | 2026031109544604758 | 2026-03-11 09:54:46 | 박진희 / Platform Engineering그룹 | 사용법 문의 | ingress rate limit 문의 (Nginx Ingress annotation limit-rate 설정 방법 및 Header/Path 복합 조합 담당자 안내) | 처리완료 |
| [8] | 2026031017454401399 | 2026-03-10 17:45:44 | 박진희 / Platform Engineering그룹 | 사용법 문의 | ingress rate limit 문의 (상세 정보 누락 건으로 재등록 VOC로 연계 처리) | 처리완료 |
| [9] | 2026031009431094950 | 2026-03-10 09:43:45 | 조재현 / 솔루션MSP그룹 | 기타 | Container Dump 파일 Download 방법 가이드 문의 (컨테이너 내부 데이터는 사용자 관리 영역으로 콘솔 외부 업로드 안내) | 처리완료 |
| [10] | 2026030917570492036 | 2026-03-09 17:57:04 | 김철호 / 전자파트너 | 기타 | Ad PaaS -> DKS 전환 관련 문의 (SDS PaaS 대비 K8s v1.26 환경 차이, People360 레퍼런스 및 전환 가이드 안내) | 처리완료 |
| [11] | 2026030909451185227 | 2026-03-09 09:45:11 | 안도원 / 생산자동화IT그룹 | 방화벽/네트워크 문의 | dks 방화벽 신청 & 네임스페이스 권한 추가 (One Cloud Project 멤버 추가 기반 NS 권한 부여 및 Outbound 방화벽 가이드) | 처리완료 |

---

## [1] P-DEP FTP 통신 위한 DKS 방화벽 해제 IP 주소 관련 문의

- **VOC 번호**: 2026031310191224424
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-13 10:19:12

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**한주형(hanjoo88.han)/Sensor PA팀(S.LSI)**
> - Project명: SensorDev
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: sios-prod
> 안녕하세요. S.LSI 한주형입니다.
> 부서 내 생산된 데이터를 DataLake에 적재하고자 사내 DataLake File Publish 서비스를 활용하고자 하고 있습니다.
> ETL의 소스 시스템으로 DKS 리소스(P-DEP)를 사용하고자하여 DKS 방화벽 해제 IP 관련 문의 드리고자 VOC 드립니다.
> File Publish 서비스의 가이드 문서에 따르면 소스 시스템 → File Publish 시스템 간 FTP 통신 위해 방화벽 해제가 필요합니다.
> 부서에서 등록한 AA 시스템(Sensor PA 통합 API)으로 P-DEP 서비스 이용하여 DKS 자원 활용 중에 있으며,
> 이 P-DEP 플랫폼을 이용하여 부서 내 생산 데이터를 File Publish 시스템 내 데이터를 적재하고자 합니다.
> 이에 P-DEP 사용 가능성에 대해 File Publish 담당자께 방화벽 해제 관련 VOC를 드렸고, 아래와 같은 답변을 주셨습니다.
> 사내 DKS 시스템 구조를 잘 몰라서 정확히 어느 단의 IP를 소스로 지정하여 방화벽을 해제할 수 있는지 잘 모르겠는데요.
> 우선 제 namespace (prd-apps-pb01-khm 클러스터) 상에서 확인되는 Ingress의 LoadBalancers IP 주소는 아래와 같습니다.
> 해당 Ingress의 IP 주소를 소스 IP로 하여 방화벽 해제를 진행하면 File Publish 시스템으로 FTP 통신을 할 수 있을지,
> 혹은 다른 프록시 IP 주소 선정이 필요한지 문의드립니다.

**조(dsec********)/Cloud Solution그룹(AI센터) (dsec25527.id)** · [게시됨] · 등록일: 2026-03-13 11:42:15
> 안녕하세요. DKS 운영팀 입니다.
> DKS(prd-apps-pb01-khm) → File Publish로 FTP 통신을 하기 위한 Source IP 대역은 다음과 같습니다.
> - 10.172.102.0/24
> - 10.172.118.0/24
> 감사합니다.

---

## [2] DKS IP 대역 문의

- **VOC 번호**: 2026031307400622363
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-13 07:40:06

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김용수(yongsuu.kim)/설비/인프라IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 사전 작업 - DS Wikipedia - DS Confluence
> (DKS콘솔) Ingress 배포 - DS Wikipedia - DS Confluence
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: MESSI
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: messi-ai-prod
> 해당 Namespace에 구동되고 있는 Pod에서 저희 시스템(MESSI) DB로 방화벽 해제를 하려고 하는데,
> 혹시 해당 Cluster의 IP 대역을 알 수 있을까요?

**조(dsec********)/Cloud Solution그룹(AI센터) (dsec25527.id)** · [게시됨] · 등록일: 2026-03-13 11:41:56
> 안녕하세요. DKS 운영팀 입니다.
> DKS(prd-apps-pb01-khm) → DB 통신을 하기 위한 Source IP 대역은 다음과 같습니다.
> - 10.172.102.0/24
> - 10.172.118.0/24
> 감사합니다.

---

## [3] DKS 자원의 OS 버전과 Kubernetes 버전 문의

- **VOC 번호**: 2026031213192417165
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-03-12 13:19:24

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**이재민(jaemin0.lee)/MTC AX/PI팀(글로벌 제조&인프라총괄)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: 없음
> - Cluster명: 없음
> - Namespace명: 없음
> 안녕하세요. 글앤총 A-FAB기술팀 이재민입니다.
> DKS 관련 궁금한 점이 있어 VOC 작성합니다.
> DKS 신청 후 자원을 받으면 해당 자원의 OS 버전과 Kubernetes 버전이 궁금합니다.
> 좋은 하루 되세요. 감사합니다.

**조(dsec********)/Cloud Solution그룹(AI센터) (dsec25527.id)** · [게시됨] · 등록일: 2026-03-12 15:33:48
> 안녕하세요. DKS 운영팀 입니다.
> OS 버전과 Kubernetes 버전은 아래와 같습니다.
> - OS 버전 : RHEL 8.6
> - Kubernetes 버전 : v1.26
> 아래 링크를 통해 자세한 가이드를 확인해주시기 바랍니다.
> https://confluence.samsungds.net/spaces/DUOKNOWHOW/pages/1051974517/DKS+%ED%91%9C%EC%A4%80+%EC%9A%B4%EC%98%81+%EC%A0%95%EC%B1%85

---

## [4] ingress통한 접속시 bad gateway 에러

- **VOC 번호**: 2026031118270611712
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-11 18:27:06

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)**
> 안녕하세요,
> https://ssqsapi.dev.flops.samsungds.net/ 로 연결 시도시 저런 에러가 발생합니다.
> 예전에 잘되던 Ingress인데 안되어서 문의글 남깁니다.
> 참고로, 해당 주소를 다른 ingress에서 사용했다가, 해당 ingress를 삭제하고, 재생성한 것이라서, 특이점이 있는 것인지 확인한번 부탁드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-12 09:58:59
> 안녕하세요. DKS 운영입니다.
> 502 에러는 Pod 문제나 포트 연결 설정등 다양한 문제로 발생할 수 있기에 기재 해주신 정보만으로는 확인이 불가합니다.
> 프로젝트, 클러스터, 네임스페이스 정보를 주시면 다시 확인 후 답변 드리겠습니다.
> 감사합니다.

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-12 11:00:55
> 클러스터 : prd-apps-pb01-khm
> 프로젝트 : YMS-Batch-ETL
> NS : yms-batch-prod
> ingress명 : mem-ssqs--mem-ssqs-backend-prod-ing
> 입니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-12 11:41:27
> 안녕하세요. DKS 운영입니다.
> 1. 말씀하신 인그레스 (mem-ssqs--mem-ssqs-backend-prod-ing) 는 mem-ssqs--mem-ssqs-backend-prod-svc 서비스로 연결 되고
> 2. mem-ssqs--mem-ssqs-backend-prod-svc 의 Selector 구성은 아래와 같습니다.
>    - app=mem-ssqs--mem-ssqs-backend-prod
> 3. 허나, Pod 중에 app=mem-ssqs--mem-ssqs-backend-prod 를 Label로 갖는 Pod가 없어 연결할 수 없는 상태입니다.
> 대상 Pod가 정상 구동중인지 확인하여 주시고, 정상 구동중이라면 Label 설정이 올바른지 확인 부탁드립니다.
> 감사합니다.

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-12 13:39:19
> 죄송합니다, 정보를 잘못전달드렸네요.
> 아래 정보로 다시 한번 부탁드립니다.
> 클러스터 : dev-apps-pb01-khs
> 프로젝트 : YMS-Batch-ETL
> NS : yms-batch-dev
> ingress명 : mem-ssqs--mem-ssqs-backend-dev-ing

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-12 15:16:11
> 안녕하세요. DKS 운영입니다.
> 대상 Pod가 liveness probe failed 로 연결이 정상적이지 않은 부분을 확인.
> 요청자님께서 해당 부분 원인 파악하시어 직접 조치하는 것으로 연락받아 종료 처리 합니다.
> 감사합니다.

---

## [5] PDEP 정상 배포 이후 사이트 접속시 404 및 무한Redirect 오류

- **VOC 번호**: 2026031118241311694
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-03-11 18:24:13

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**이강길(dsgl08691.id)/Data Platform그룹(AI센터)**
> 안녕하세요. 사외업무시스템 운영팀 이강길입니다.
> PDEP 에서 배포 이후
> URL : https://devops.samsungds.net/product/product_detail_k8s?systemid=backoffice@serviceid=backoffice-v1-dev
> AA Module Name : SWFAS
> Product Group ID or Name : backoffice
> Product ID or Name : backoffice-v1-dev
> CI/CD를 배포실행 한 후 접속해보니 https://swfas-backoffice-dev.samsungds.net/ 오류페이지가 나왔습니다.
> 어제까지 배포 할땐 이런 문제가 없었는데 갑자기 오늘부터 문제가 발생했습니다. (404 오류 혹은 무한 리다이렉션 오류)
> 확인 부탁드립니다. ㅠ
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-12 11:36:59
> 안녕하세요. DKS 운영팀입니다.
> https://swfas-backoffice-dev.samsungds.net 접속시 404 에러가 발생하는 건에 답변드립니다.
> 해당 도메인에 대한 ingress controller의 access log 상에서
> 서비스(teleworksystem-update-prod-backoffice--backoffice-v1-dev-svc-80) -> Pod(192.223.28.245:8080)까지 전달되었으나 404 응답을 한 것으로 확인됩니다.
> ```text
> [prd-apps-pb01-khm:console-test] $ kubectl -n ingress-nginx logs -f --tail 10 -l app.kubernetes.io/instance=ingress-nginx | grep 404 | grep telework
> 127.0.0.1 - - [12/Mar/2026:02:14:42 +0000] "GET / HTTP/2.0" 404 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0" 504 0.005 [teleworksystem-update-prod-backoffice--backoffice-v1-dev-svc-80] [] 192.223.28.245:8080 0 0.005 404 c2b3ab23ba5cfa14fd3d8ed13cfe8ed9 teleworksystem-update-prod
> ```
> 어플리케이션을 확인해보시고 다른 문제가 있으시면 다시 문의부탁드립니다.
> 감사합니다.

---

## [6] 웹콘솔 권한 확인

- **VOC 번호**: 2026031112004206492
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-11 12:00:42

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**전희광(heekwang.jeon)/DS IT그룹(전자/제조IT)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: Digital-HR-Platform
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: hrtalentview-dev
> DKS에서 웹콘솔에 접속하여 pod 모니터링을 하려고 했으나 권한이 부족한 것인지 아래와 같은 메시지가 발생하고 있습니다.
> 조치 가이드 부탁드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-13 16:32:10
> 안녕하세요. DKS 운영입니다.
> 답변이 늦어 죄송합니다.
> 문의 주신 내용에 대해 검토 결과 내부 문제를 확인하였습니다.
> 적용 및 배포 프로세스에 따라서 차주 수요일경 해당 부분 수정하여 적용 예정입니다.
> 불편하시더라도 그 전까지는 DKS Console UI를 이용하여 확인 부탁드리며, 적용 이후에 웹콘솔 사용 부탁드립니다.
> 감사합니다.

**전희광(heekwang.jeon)/DS IT그룹(전자/제조IT)** · [게시됨] · 등록일: 2026-03-16 14:45:09
> 안녕하세요.
> 확인 감사드립니다.
> DKS Console UI 가 아래 화면을 말씀하시는걸까요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-16 17:07:36
> 안녕하세요. DKS 운영입니다.
> 네 DKSCTL 기능을 제외한 웹 UI 기능을 이야기 드린게 맞습니다.
> 인그레스에 대한 확인은 답변 주신 화면을 이용하시면 되고,
> 최초 요청하셨던 Pod 모니터링을 위해서는 Workload > Pods 메뉴를 이용 부탁드립니다.
> 웹콘솔 기능에 대한 패치 일정이 3월 23일로 확정되었습니다.
> 적용 이후에는 정상적으로 웹콘솔 이용이 가능합니다.
> 불편을 드려 죄송합니다.
> 감사합니다.

---

## [7] ingress rate limit 문의

- **VOC 번호**: 2026031109544604758
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-11 09:54:46

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**박진희(jinnie.park)/Platform Engineering그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> 안녕하세요. 이전 voc 에서 사용중인 project, cluster, namespace 에 대한 정보가 누락되어 voc 재 등록드리는 건 입니다.
> 이전 voc link : https://service-hub--sh-servicehub-prod.kspprd.dks.cloud.samsungds.net/sh/svoc/voc/list?vocId=2026031017454401399&myVoc=false
> DKS 에서 ingress controller 를 사용해 ingress 에 rate limit 을 걸고 싶은데 혹시 가능한지 알 수 있을까요?
> - Project명: DataLakeService
> - Cluster명: prod-ds-member-dev
> - Namespace명: bdqrestapi-dev
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-11 11:48:54
> 안녕하세요. DKS 운영입니다.
> 이미 사용하시는 Ingress가 있으신 것으로 생각되며, 아래와 같은 절차로 설정 가능합니다.
> 1. DKS에 접속하셔서 Network > Ingresses 메뉴에 접속하신 후 원하시는 Ingress를 선택하여 "수정" 합니다.
> 2. 설정은 Annotation 으로 가능하며, 아래 링크를 참고하시어 수정하시면 됩니다.
>    - Ingress Rate Limiting 설명 : https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting
>      (limit-rate 사용을 위해서는 proxy-buffering 설정을 "on" 해야 함에 유의)
>    - 실제 입력값 참고 : https://oneuptime.com/blog/post/2026-02-09-rate-limiting-ingress-api-protection/view#rate-limiting-with-nginx-ingress-controller
> 감사합니다.

**박진희(jinnie.park)/Platform Engineering그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-11 14:25:25
> 안녕하세요.
> 우선 상세한 답변 감사합니다.
> 이후 메신저 보내주신 내용에 대해 추가 문의드립니다.
> client ip 기반으로 rate limit 설정하는 것이 아닌, 인그레스 통해 트래픽이 들어올 때 Header 와 Path 조합으로 rate limit 을 걸고 싶습니다.
> 예를 들어 header 에 user-name: jinnie.park, path 에 {project-id} -> 'test-prj' 가 파라미터로 하여 인그레스로 트래픽이 들어올 때
> 'jinnie.park', 'test-prj' 조합으로 rate limit 설정이 가능한 걸까요?
> 특정 user-name 헤더값, 특정 project-id path 값이 아닌 헤더 header(user-name) & path parameter(project-id) 조합으로 rate limit 을 걸고 싶습니다.
> 제가 설명이 부족했을 수도 있는데 문의 내용이 잘 확인되지 않는다면 메신저 주셔도 좋습니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-11 16:34:43
> 안녕하세요. DKS 운영입니다.
> 추가로 문의주신 내용에 대해서는 삼성전자 담당자분께 메일로 문의주셔야 할 것 같습니다.
> 담당자 정보는 메신저로 전달 드리겠습니다.
> 감사합니다.

---

## [8] ingress rate limit 문의

- **VOC 번호**: 2026031017454401399
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-10 17:45:44

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**박진희(jinnie.park)/Platform Engineering그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명:
> - Cluster명:
> - Namespace명:
> 안녕하세요.
> DKS 에서 ingress controller 를 사용해 ingress 에 rate limit 을 걸고 싶은데 혹시 가능한지 알 수 있을까요?
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-11 10:23:17
> 안녕하세요. DKS 운영입니다.
> 본 VOC는 아래 링크(2026031109544604758)로 처리 예정입니다.
> https://service-hub--sh-servicehub-prod.kspprd.dks.cloud.samsungds.net/sh/svoc/voc/list?vocId=2026031017454401399
> 감사합니다.

---

## [9] Container Dump 파일 Download 방법 가이드 문의

- **VOC 번호**: 2026031009431094950
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-03-10 09:43:45

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**조재현(jh82.cho)/솔루션MSP그룹(솔루션운영)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: 메모리 제품 테스트 플랫폼
> - Cluster명: prod-ds-member
> - Namespace명: testplatform-prod
> 안녕하세요.
> Memory 사용 관련 확인이 필요해 Container 콘솔에서 Dump 파일을 생성했습니다.
> Memory 사용 이슈로 콘솔상에서 Dump 파일 확인이 어려워 파일을 Download 받고 싶은데, 해당 파일 Download 방법 가이드 또는 Download 후 전달이 가능할지 문의드립니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-10 16:42:59
> 안녕하세요. DKS 운영팀 입니다.
> 컨테이너 내의 데이터는 사용자 관리 영역으로 DKS에서 관여하지 않으며 다운로드, 백업 등을 지원하지 않습니다.
> 필요시 컨테이너 콘솔에서 외부 저장소로 직접 업로드 하셔야 하고,
> 방화벽 정책에 따라 일부 외부 저장소는 통신이 불가할 수 있습니다.
> 감사합니다.

---

## [10] Ad PaaS -> DKS 전환 관련 문의

- **VOC 번호**: 2026030917570492036
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-03-09 17:57:04

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김철호(chulhop.kim)/전자파트너**
> 안녕하세요.
> P360 홈위젯/CCC ITO 김철호 입니다.
> 현재 운영 시스템 인프라 환경으로 Ad PaaS를 사용하고 있으나, EOS 이슈로 DKS 전환을 고려하고 있습니다.
> 관련하여 다음 내용 문의드립니다.
> 1. DKS로 운영환경을 전환하고자 할 경우 필요한 사전 준비작업이 어떤 것이 있는지 알고싶습니다.
> 2. 앞서 혹은 현재 진행중인 DKS 전환 사업이 있는지, 있다면 래퍼런스로 참고할만한 문서가 있는지 알고싶습니다.
> 3. DKS에 대한 아키텍처 등 참고해야할 문서와 매뉴얼이 있는지 알고싶습니다.
> 4. Ad PaaS와 DKS에 대한 비교 문서가 있는지 알고싶습니다.
> 확인 부탁드립니다.
> 감사합니다.
> 김철호 드림.

**윤신수(ss_bv.yun)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-09 19:49:40
> 안녕하세요. Cloud Platform 윤신수입니다.
> SDS PaaS를 운영하셨기 때문에 k8s에 대해서는 어느정도 이해가 있으신 것으로 이해한다면
> 먼저 아래의 Guide 를 확인해보시면 DKS에서 필요한 부분에 대해서는 어느정도 아실 것 같긴 합니다.
> - 가이드: https://confluence.samsungds.net/spaces/DUOKNOWHOW/pages/859876849
> - DKS 콘솔: https://dks.samsungds.net/
> 
> 별도의 Reference 문서는 보유하고 있지는 않지만 아래의 People360 관련한 Resource(Namespace) 가 이미 DKS 위에서 동작하고 있으니 참고하시면 될 것 같습니다.
> 기본적으로 SDS PaaS 는 CI/CD + k8s로 구성되어 있으며 k8s Version 은 1.17(Prod), 1.19(dev) 를 활용하고 있으며,
> DKS 는 k8s(1.26)의 Infra를 제공하고 있고 CI/CD 는 P-DEP or 자체 Web Console(DKS) 을 통해서 배포가 가능합니다.
> 
> [People360 연관 운영 네임스페이스 현황]
> - dev-apps-pb01-khs (DEV): grp-core-dev, grp-core-stg, grp-ext-dev, grp-ext-stg, grp-fe-dev, grp-fe-stg, grp-infra-dev, grp-infra-stg, grp-mgmt-dev, grp-mgmt-stg, grp-support-dev, grp-support-stg (RECRUIT-PORTAL / AP20250714001)
> - prd-apps-pb01-khm (PROD): grp-core-prod, grp-ext-prod, grp-fe-prod, grp-infra-prod, grp-mgmt-prod, grp-support-prod (RECRUIT-PORTAL / AP20250714001)
> - prod-ds-member (PROD): hrsolution-prd (beyourself / AP20240827002)
> - prod-ds-member-dev (DEV): hrsolution-dev (beyourself / AP20240827002)
> 감사합니다.

---

## [11] dks 방화벽 신청 & 네임스페이스 권한 추가

- **VOC 번호**: 2026030909451185227
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-09 09:45:11

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**안도원(dowon.ahn)/생산자동화IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 사전 작업 - DS Wikipedia - DS Confluence
> (DKS콘솔) Ingress 배포 - DS Wikipedia - DS Confluence
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: ui-airflow
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: ui-airflow-prod
> 안녕하세요. 생산자동화IT그룹 안도원입니다.
> 2가지 문의 드립니다.
> 1. 해당 클러스터 내 서버를 띄우고 타 시스템 api 호출을 하려고 하니, 타임아웃이 발생합니다. 방화벽 문제로 보이는데 방화벽 신청 가이드 요청드립니다.
>    `[2026-03-07, 14:45:41 KST] {call_ees_api.py:135} ERROR - getEesApiResult Error : HTTPConnectionPool(host='10.138.241.38', port=8600): Max retries exceeded with url: /KH.SWP.Server.RestAPIApp/RestAPIService.svc/rms/eco (Caused by ConnectTimeoutError(, 'Connection to 10.138.241.38 timed out. (connect timeout=10)'))`
> 2. 네임스페이스에 대한 권한은 어떻게 추가할 수 있을까요?

**윤신수(ss_bv.yun)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-09 19:55:45
> 1. 권한 관련해서는 DKS 는 One Cloud 의 Project 권한을 상속받고 있습니다.
>    따라서 Namespace 의 권한 추가를 원하시면 해당 Project 에 먼저 Member 추가 후 DKS 에서 권한을 추가적으로 부여하시면 됩니다.
> 2. 방화벽 관련해서는 Source , Destination을 확인하신 후 아래의 Wiki를 참고하여 Open 하시면 됩니다.
>    해당 Namespace 는 "prd-apps-pb01-khm" 로 확인됩니다. 참고하세요.
>    방화벽 Open 은 어떻게 하나요? - DS Wikipedia - DS Confluence
> 감사합니다.
