# VOC 목록 — DS Cloud / 가상 자원(Container)-DKS (2026-02-22 ~ 2026-02-28)

- **수집 기간**: 2026-02-22 ~ 2026-02-28
- **시스템/세부시스템**: DS Cloud > 가상 자원(Container)-DKS
- **전체 건수**: **7건**

---

## 요약 목록

| 번호 | VOC 번호 | 등록일시 | 문의자 / 부서 | 문의 유형 | 제목 / 핵심 내용 | 상태 |
|:---:|:---:|:---:|:---|:---:|:---|:---:|
| [1] | 2026022613431630513 | 2026-02-26 13:43:16 | 조성재 / Generative AI팀 | 수요/자원 문의 | DS VM 자원의 DKS 이전 가능 여부 문의 (Cloud VM 자원과 DKS 자원은 별도 운영 자원으로 이관/변경 불가 안내) | 처리완료 |
| [2] | 2026022612410229905 | 2026-02-26 12:41:02 | 김진철 / AX전략그룹 | 사용법 문의 | DKS 외부 방화벽 해제 문의 (사외 Huggingface 등 인터넷 직접 통신 제한, 보안정책상 사내 Repo 경유 및 클러스터 공유 영향 설명) | 처리완료 |
| [3] | 2026022611160529134 | 2026-02-26 11:16:05 | 임정원 / Cloud Solution그룹 | 장애/오류 접수 | service account 생성후 키가 보이지 않습니다 (K8s 1.24+ 보안 정책에 따른 Secret 자동생성 미지원 및 수동 Token 생성 가이드 안내) | 처리완료 |
| [4] | 2026022610255828376 | 2026-02-26 10:25:58 | 강경태 / 설비/인프라IT그룹 | 방화벽/네트워크 문의 | Ingress Nginx body size 제한 설정 문의드립니다 (Ingress annotation `proxy-body-size: "0"` 추가를 통한 제한 해제 설정 안내) | 처리완료 |
| [5] | 2026022517064524918 | 2026-02-25 17:06:45 | 김동규 / Design Technology팀 | 장애/오류 접수 | ingress-controller 로그 요청 (C-DEP 502 Bad Gateway 로그 확인 결과 헤더 사이즈 이슈 규명 및 Ingress annotation 수정 안내) | 처리완료 |
| [6] | 2026022411561713187 | 2026-02-24 11:56:17 | 곽진철 / PLM기술그룹 | 기타 | prd-apps-pb01-khm 클러스터 ui-airflow-prod NS Pod 생성 주기 추가 문의 (단기 배치 파드 잦은 생성으로 인한 Prometheus OOM 발생, 상시 파드 전환 일정 조율) | 처리완료 |
| [7] | 2026022311243204451 | 2026-02-23 11:24:32 | 윤승현 / 설비/인프라IT그룹 | 기타 | 자원 사용량 문의 (저활용 회수 대응을 위한 yms-batch 네임스페이스별 실사용량 CPU/MEM AVG 및 MAX 통계 정정 제공) | 처리완료 |

---

## [1] DS VM 자원의 DKS 이전 가능 여부 문의

- **VOC 번호**: 2026022613431630513
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-02-26 13:43:16

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**조성재(sjae.cho)/Generative AI팀(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: docpamin
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: docpamin-dev
> Cloud VM 자원을 DKS로 변경 가능한지 문의드립니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 15:43:47
> 안녕하세요. DKS 운영팀 입니다.
> VM 자원과 DKS 자원은 별도 자원으로 운영되고 있으며
> 자원 이관 및 변경이 불가합니다.
> 감사합니다.

---

## [2] DKS 외부 방화벽 해제 문의

- **VOC 번호**: 2026022612410229905
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-02-26 12:41:02

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김진철(jinpro95.kim)/AX전략그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> ----------------------------------------------------------------------------------------------------------------------------
> 안녕하세요.
> 질문 드립니다.
> DKS Pod -> 외부 시스템로의 통신이 필요합니다 - DS Wikipedia - DS Confluence
> 위 가이드를 보면,
> DKS 내 Huggingface 등 외부 URL 주소에서 데이터를 fetch로 들고온다고 할 때, 위 방화벽 해제를 진행할 경우 DS Cloud 와 외부 소스간 데이터 수집이 가능할까요?
> 질문 드립니다.
> ----------------------------------------------------------------------------------------------------------------------------
> - Project명:
> - Cluster명:
> - Namespace명:

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 12:53:17
> 안녕하세요. DKS 운영팀 입니다.
> DKS에서의 구조 상으로는 src: DKS, dst: 외부 인터넷 으로 방화벽 해제가 된다면
> 통신이 가능할 수는 있습니다.
> 하지만, DKS에서 사용하고 있는 VM(노드) 는 따로 서버망 네트워크 내에 있는 것으로 알고 있고
> 서버망 <-> 외부 인터넷 간에 통신에 대해 보안 부서에서 제한할 수 있어서
> 저희가 확답을 드리기 어려운 점이 있습니다.
> 이에 대해서는 보안 부서, 방화벽(GSAMS) 쪽으로 확인이 필요하실 것 같습니다.
> https://gsams.samsungds.net/portal/main.do
> 감사합니다.

**김진철(jinpro95.kim)/AX전략그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-02-26 13:03:52
> 안녕하세요. 답변 감사드립니다.
> | 용도 | 클러스터명 | 대역대 |
> |---|---|---|
> | DKS 범용 Cluster | prod-ds-member | 10.172.33.0/24, 10.172.34.0/24 |
> | DKS 범용 Cluster | prod-ds-member-dev | 10.172.33.0/24, 10.172.34.0/24 |
> | DKS 범용 Cluster | prd-apps-pb01-khm | 10.172.34.0/24, 10.172.102.0/24, 10.172.118.0/24 |
> | DKS 범용 Cluster | dev-apps-pb01-khs | 10.166.113.0/24 |
> | C-DEP Cluster | prod-ds-citizen | 10.172.33.0/24 |
> | C-DEP Cluster | prd-ctzs-pb01-khs | 10.166.113.0/24, 10.166.144.0/24 |
> | C-DEP Cluster | prd-ctzj-pb01-khs | 10.166.113.0/24, 10.166.144.0/24 |
> 가이드를 보면, 제 클러스터 노드는 dev-apps-pb01-khs 에 떠있는 것으로 보이는데,
> 제가 만약 GSAMS에서 10.166.113.0/24 -> Huggingface TCP 연동을 하도록 방화벽 해제를 한다면,
> 이 경우 클러스터 내 다른 프로젝트도 모두 적용되도록 될 것 같은데... 이런 것은 상관없는걸까요?

**윤신수(ss_bv.yun)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-02-26 13:13:37
> 안녕하세요.
> 허깅페이스에 연결하려고 하시는 사유가 모델이나 data Set등의 download를 위해서일까요?
> 그렇다고 하시면 사내의 Repo 를 통하여 방화벽 해제 및 model 검증을 통한 Download 하심이 맞을 것 같습니다.
> 위와같이 방화벽을 뚫고자 하였을 때 보안그룹에서 해 주시지 않을 것으로 예상되며
> 말씀하셨던 바와 같이 전체 Cluster 에 영향을 받게 됩니다.

**김진철(jinpro95.kim)/AX전략그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-02-26 13:17:54
> 안녕하세요. 윤신수 파트장님.
> 답변 감사드립니다.
> 현재, 파트 내에 오픈소스 모델 트렌드 센싱 에이전트 구현을 진행 중이라,
> DKS 내에서 Huggingface / Openrouter에서 제공해주는 API (Inbound)를 활용해 DBaaS에 저장하고자 하였습니다.
> 말씀주신 것처럼 불가능한 것으로 판단하고, VM이나 자체 서버에서 진행하는 것으로 하겠습니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 16:44:15
> 안녕하세요. DKS 운영팀 입니다.
> 더 궁금하신 내용, 확인이 필요한 내용 있으시다면 추가 문의주시기 바랍니다.
> 문의 주셔서 감사합니다.
> VOC 종료하겠습니다.

---

## [3] service account 생성후 키가 보이지 않습니다.

- **VOC 번호**: 2026022611160529134
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-02-26 11:16:05

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**임정원(callist.lim)/Cloud Solution그룹(AX/PI센터)**
> 안녕하세요 아래에 service account 생성후 키가 보이지 않습니다.
> 오류 처리 부탁드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 11:23:35
> 안녕하세요. DKS 운영팀 입니다.
> Kubernetes 클러스터 1.24 버전부터는 보안상의 이유로 Secret이 자동 생성되지 않습니다.
> 아래 링크를 통해 자세한 가이드를 확인해주시기 바랍니다.
> Service Account + Token 생성하기 - Cluster 1.24버전 이상 - DS Wikipedia - DS Confluence
> 감사합니다.

---

## [4] Ingress Nginx body size 제한 설정 문의드립니다.

- **VOC 번호**: 2026022610255828376
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-02-26 10:25:58

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**강경태(kobe.kang)/설비/인프라IT그룹(AX/PI센터)**
> - Project명: FMCS Portal
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: fmcs-common-service-web-proc-prod
> FMCS Portal용 Ingress (fmcs--fmcs-portal-dks-prod-ing)가 ingressClassName: nginx 지정해서 NGINX Ingress Controller를 사용 중으로 알고 있습니다.
> Ingress Nginx에 body size 제한에 대한 설정이 없어, 413 Error가 종종 발생하고 있습니다.
> Ingress annotation에 아래와 같이 proxy-body-size 정보 추가해서 body size 제한을 해제할 수 있는지 문의드립니다.
> ```yaml
> metadata:
>   annotations:
>     nginx.ingress.kubernetes.io/proxy-body-size: "0"
> ```

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 11:32:36
> 안녕하세요. DKS 운영팀 입니다.
> 네 DKS는 k8s ingress nginx controller 를 사용하기 때문에 말씀하신 annotation 값을 통해 설정 가능합니다.
> 관련하여 자세한 내용은 아래 링크의 ingress-nginx 공식 문서를 참고해주시기 바랍니다.
> Annotations - Ingress-Nginx Controller
> 감사합니다.

---

## [5] ingress-controller 로그 요청

- **VOC 번호**: 2026022517064524918
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-02-25 17:06:45

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김동규(dong05.kim)/Design Technology팀(S.LSI)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명:
> - Cluster명:
> - Namespace명:
> 안녕하세요.
> C-DEP에 502 bad gateway 관련하여 nginx로그 문의 결과 해당 로그는 DKS에서 가지고 있다고 하여 문의드립니다.
> C-DEP 운영환경에서 인증 후 다시 callback될 경우 아래와 같이 nginx에서 bad gateway오류가 발생합니다.
> 위와 같은 이유로 C-DEP 운영환경의 k8s의 ingress-controller의 로그가 필요합니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-26 15:49:10
> 안녕하세요. DKS 운영팀 입니다.
> 메일 통하여 로그 전달 드렸으며, 확인 결과 header size 관련 이슈로 보입니다.
> DKS에서는 k8s ingress nginx를 사용하고 있으며
> 아래 문서에서와 같이 ingress의 annotation 작성을 통해 설정을 변경할 수 있습니다.
> https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
> 문의자분께서 C-DEP을 활용하고 계셔서 수정 방법에 대해서는 C-DEP으로 문의 부탁드립니다.
> 감사합니다.

---

## [6] prd-apps-pb01-khm 클러스터 ui-airflow-prod NS Pod 생성 주기 추가 문의

- **VOC 번호**: 2026022411561713187
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-02-24 11:56:17

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**곽진철(jc.gwak)/PLM기술그룹(디지털PLM)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: P-DEP
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: oprsvc-prod
> 이전 문의 내용 :
> https://service-hub--sh-servicehub-prod.kspprd.dks.cloud.samsungds.net/sh/svoc/voc/list?vocId=2026021217281176273&myVoc=false
> 안녕하세요.
> 이전 문의에서 prd-apps-pb01-khm 클러스터 ui-airflow-prod 네임스페이스에서 과도한 Pod 재생성이 발생하고 있다고 확인 해주셨습니다.
> 확인 감사드립니다.
> 말씀하신것처럼 해당 네임스페이스에서 airflow 의 KubernetesPodOperator 를 사용하시는것 같습니다.
> 해당 네임스페이스 에서 발생하는 메트릭으로 인해 prd-apps-pb01-khm 클러스터에 배포된 프로메테우스가 메모리 부하가 상당한 상황입니다.
> OOM 으로 인한 장애가 발생해서 일단은 임시로 prd-apps-pb01-khm 클러스터 내의 프로메테우스 메모리 증설을 해서 조치를 해둔 상태 입니다.
> 현재도 초단위로 계속 Pod 가 재생성 되고 있는데 조정이 가능한 부분인지 문의 드립니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-24 17:01:47
> 안녕하세요. DKS 운영팀 입니다.
> 관련하여 ui-airflow-prod 담당자분께서 주기가 짧은 task에 대해서 상시 pod로 변경을 검토해보겠다고 합니다.
> 다만, 조치는 2~3주 길게는 3월 중으로 될 것 같다고 하셔서 그동안에는 해당 현상이 지속될 것으로 보입니다.
> 참고 바랍니다.
> 아래 대화 나누었던 담당자분 정보와 대화 전문을 함께 전달 드립니다.
> 감사합니다.
> ---
> ui-airflow-prod 담당자: 안도원 dowon.ahn@samsung.com
> 
> [대화 전문]
> [DKS 운영] 2026-02-24 16:25 : 안녕하세요. DKS 운영팀 입니다.
> [DKS 운영] 2026-02-24 16:30 : ui-airflow-prod 네임스페이스 담당자분 맞으실까요? 저희 쪽에 접수된 문의와 관련해서 여쭤볼 내용이 있어서 연락드렸습니다.
> [안도원] 2026-02-24 16:37 : 안녕하세요 넵 맞습니다
> [DKS 운영] 2026-02-24 16:38 : P-DEP 쪽에서 최근에 모니터링 쪽 컴포넌트에 메모리 사용률이 증가해서 저희가 같이 확인을 해보니 ui-airflow-prod 에서 최근 pod 생성, 삭제가 빈번해서 영향이 있는 것 같은 상황입니다. 혹시 이런 상황이 앞으로도 지속되는 걸까요?
> [DKS 운영] 2026-02-24 16:39 : 아니면 당분간만이고 이 후에는 좀 진정이 되는지
> [안도원] 2026-02-24 16:39 : 아 저희가 배치잡을 돌리는데, 배치 task 마다 파드 띄우고 종료하는구조라 계속 될 예정인데요 혹시 운영에 문제가 있을까요?
> [DKS 운영] 2026-02-24 16:41 : P-DEP 쪽에서 관련해서 메모리 사용률 증가로 인한 OOMkill이 발생하고 있다는 것 같습니다. 그리고 저희 DKS 쪽에서도 아마 pod가 자주 배포되고 삭제되면 다른 pod 들이 배포될 때 지연이 발생할 가능성도 있을 것 같습니다. 그리고 저희가 지표를 살펴보니 적을 때는 10분에 20개 안밖으로 배포가 되다가 한 100개 까지 배포되기도 하시던데 이런 상황이 지속된다는 말씀이시죠?
> [안도원] 2026-02-24 16:42 : 아 네네,, 저번에 api 에러율 문의를 주셨던적도 있는데 이건 좀 내려갔을까요? 그리고 해당 클러스터에서 파드 생성 갯수 제한이 있을까요~?
> [DKS 운영] 2026-02-24 16:44 : api 관련해서는 다른 담당자분이 봐주셨던 것 같아요.
> [안도원] 2026-02-24 16:46 : 어떤 k8s 컴포넌트가 OOM 나는지도 궁금합니다
> [DKS 운영] 2026-02-24 16:46 : P-DEP 쪽에서는 prometheus 라고 합니다
> [안도원] 2026-02-24 16:46 : 파드가 자주 뜨는게 문제라면.. 주기가 짧은 태스크들은 상시 파드로 데이터 생성하는걸로 바꿀수는 있는데 시간이 2~3주 정도 걸릴 수 있어요
> [DKS 운영] 2026-02-24 16:47 : 클러스터의 pod 갯수 제한은 확인해봐야 하는데요. 일단은 CIDR 만큼(/16) 그리고 노드별로는 각 110개 정도 일 것 같습니다
> [DKS 운영] 2026-02-24 16:47 : 네 그렇게라도 조치가 된다면 도움이 될 것 같습니다. pod 배포할 때 관련 가상 이더넷이라던지, 네트워크 설정, volume mount 등 과정을 하고 또 제거될 때도 동일하게 해제를 해야 하기 때문에 작업이 많아지면 다른 pod 배포에도 영향이 있을 수 있어서 가능하시다면 추후에라도 조치해주시면 감사하겠습니다.
> [안도원] 2026-02-24 16:49 : 아 넵넵.. 운영에 문제가 생기면 안되니 3월 안으로 조치하고 회신드리겠습니다
> [DKS 운영] 2026-02-24 16:50 : 네 감사합니다. 해당 내용은 접수된 voc 답변을 통해 P-DEP 으로도 말씀을 드리겠습니다. 어쩌면 관련해서 P-DEP에서도 문의를 주실 수 있을 것 같아서 VOC 답변에 담당자분 성함을 남겨도 될까요?
> [안도원] 2026-02-24 16:50 : 넵 voc 주소도 알려주세요~
> [DKS 운영] 2026-02-24 16:52 : 아래 링크 드리겠습니다. 확인 감사합니다!
> https://service-hub--sh-servicehub-prod.kspprd.dks.cloud.samsungds.net/sh/svoc/voc/list?vocId=2026022411561713187&myVoc=false
> [안도원] 2026-02-24 16:52 : 네 감사합니다~

---

## [7] 자원 사용량 문의

- **VOC 번호**: 2026022311243204451
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-02-23 11:24:32

### 대화 내용

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)**
> YMS-BATCH-PROD (prd-apps-pb01-khm)
> YMS-BATCH-ETL-PRD (prod-ds-member)
> 두 네임스페이스의 2월 1일 부터 CPU/MEM의 MAX/AVG 사용량을 공유해주시면 감사하겠습니다.
> 저활용 회수 대응 중이고, DKS포탈의 차트로는 타점이 적어 정확한 확인이 불가능해서 요청드립니다.

**DS Cloud 서비스데스크2(dscsv2.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-02-23 11:26:05
> 안녕하세요, 클라우드 상황실입니다.
> YMS-BATCH-PROD (prd-apps-pb01-khm)
> YMS-BATCH-ETL-PRD (prod-ds-member)
> 두 네임스페이스의 2월 1일 부터 CPU/MEM의 MAX/AVG 사용량 확인이 가능한지 문의로 이관하오니 확인 부탁드리겠습니다.
> 감사합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-23 14:12:07
> 안녕하세요. DKS 운영팀 입니다.
> 지난 24일 간 데이터를 기준으로 조회한 결과를 공유 드립니다.
> | cluster | namespace | CPU AVG (Core) | CPU MAX (Core) | MEM AVG (GiB) | MEM MAX (GiB) |
> |---|---|---|---|---|---|
> | prd-apps-pb01-khm | yms-batch-prod | 211.8 | 235.5 | 766.1 | 804.8 |
> | prod-ds-member | yms-db-etl-prod | 208.6 | 250.5 | 420.8 | 467.6 |
> 감사합니다.

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-02-23 14:21:00
> 요청드린 네임스페이스 중하나는,
> yms-db-etl-prod가 아닌
> YMS-BATCH-ETL-PRD 입니다.
> 그리고, request가 얼마나 되고 있는지를 여쭌 것은 아니고, 실제로 사용률(Usage)을 문의드린 것입니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-02-23 14:52:14
> 안녕하세요. DKS 운영팀 입니다.
> 정정하여 다시 공유 드립니다.
> | cluster | namespace | CPU AVG (Core) | CPU MAX (Core) | MEM AVG (GiB) | MEM MAX (GiB) |
> |---|---|---|---|---|---|
> | prd-apps-pb01-khm | yms-batch-prod | 20.7 | 85.0 | 227.1 | 321.5 |
> | prod-ds-member | yms-batch-etl-prd | 3.6 | 6.9 | 14.2 | 20.9 |
> 혼란을 드려 죄송합니다.
> 감사합니다.
