# VOC 목록 — DS Cloud / 가상 자원(Container)-DKS (2026-05-10 ~ 2026-05-16)

- **수집 기간**: 2026-05-10 ~ 2026-05-16
- **시스템/세부시스템**: DS Cloud > 가상 자원(Container)-DKS
- **전체 건수**: **20건**

---

## 요약 목록

| 번호 | VOC 번호 | 등록일시 | 문의자 / 부서 | 문의 유형 | 제목 / 핵심 내용 | 상태 |
|:---:|:---:|:---:|:---|:---:|:---|:---:|
| [1] | 2026051517142637735 | 2026-05-15 17:14:26 | 김선우 / S/W개발팀 | 사용법 문의 | DB Pod 접근 방법 문의 (DKS-C 환경에서 LoadBalancer 타입 서비스 생성 및 외부 IP를 통한 TCP 통신 가이드) | 처리완료 |
| [2] | 2026051509123132269 | 2026-05-15 09:12:32 | 황한동 / 비즈니스플랫폼1그룹 | 수요/자원 문의 | 네임스페이스 이름변경 및 협력사 권한 문의 (K8s NS 이름 변경 불가 및 One Cloud를 통한 프로젝트 멤버 추가 절차 안내) | 처리완료 |
| [3] | 2026051417172629842 | 2026-05-14 17:17:26 | 김선우 / S/W개발팀 | 사용법 문의 | DKS 게이트웨이 배포 관련 (DKS-C Gateway API 셋업 시 TLS Secret 생성 방법 및 클러스터별 단독 Ingress IP 방화벽 오픈 안내) | 처리완료 |
| [4] | 2026051414095927533 | 2026-05-14 14:09:59 | 복병훈 / Generative AI팀 | 기타 | dks내 namespace 신청안됨 (콘솔 목록추가 버튼 오동작 이슈 조치 완료) | 처리완료 |
| [5] | 2026051409462824287 | 2026-05-14 09:46:28 | 전경민 / 생산자동화IT그룹 | 사용법 문의 | VKS 앱배포파이프라인 메뉴 버튼 권한 추가 가이드 요청 (DKS 사용자 멤버 권한 부여 조치) | 처리완료 |
| [6] | 2026051317473421401 | 2026-05-13 17:47:34 | 정연성 / Cloud Solution그룹 | 사용법 문의 | DKS console(DKS2) Cluster 서비스의 Ingress IP 문의 (Control Plane 3중화 증설 작업 완료 후 정상 노출 안내) | 처리완료 |
| [7] | 2026051313272517851 | 2026-05-13 13:27:25 | 문석호 / 품질AX/PI팀 | 사용법 문의 | AI agent 서비스 웹 애플리케이션 형태의 배포 방식 문의 (IT Cloud VM 배포 절차 및 ASRB GPU 자원 신청 가이드) | 처리완료 |
| [8] | 2026051309014214595 | 2026-05-13 09:01:42 | 강재구 / 해외파견 | 방화벽/네트워크 문의 | 방화벽해제를위한 ip/port 문의 (보안SOS 이관 및 DSDN, Assistant 접속 IP/Port 443 정보 제공) | 처리완료 |
| [9] | 2026051216565011625 | 2026-05-12 16:56:50 | 임승지 / 인프라AX/PI팀 | 기타 | 육아 휴직 시 DKS 자원 및 권한 변경에 관한 문의 (DKS 콘솔 내 대표관리자/관리자 권한 타 인력 위임 안내) | 처리완료 |
| [10] | 2026051216363611350 | 2026-05-12 16:36:36 | 박소연 / S/W Engineering팀 | 기타 | Node별 ip 대역 문의 (제어 대상 대역 외 임시 배포 노드 3대 안내 및 12.x 대역을 사용하는 DKS-C Beta 도입 권장) | 처리완료 |
| [11] | 2026051215080609968 | 2026-05-12 15:08:06 | 곽진철 / PLM기술그룹 | 사용법 문의 | 1.33 cluster kube config 설정 문의 (v1.33 APISIX API Server 401 오류 건에 대한 올바른 계정 정보 확인 및 메신저 가이드) | 처리완료 |
| [12] | 2026051210223006354 | 2026-05-12 10:22:30 | 전경민 / 생산자동화IT그룹 | 사용법 문의 | DKS2 Baseimage 가져오는 방법 가이드 요청 (자체 레지스트리 미지원 안내 및 DKS Harbor push 후 명시적 태그 사용 가이드) | 처리완료 |
| [13] | 2026051116153401388 | 2026-05-11 16:15:34 | 고석준 / S/W Engineering팀 | 장애/오류 접수 | 장애 원인 분석을 위한 호스트/CSI 로그 공유 요청 (Postgres coredump/CrashLoopBackOff 분석 및 스토리지 이상 무 확인) | 처리완료 |
| [14] | 2026051115122000391 | 2026-05-11 15:12:20 | 조희원 / AX/PI팀 | 기타 | Minio 헬름 차트 추가 요청 (DKS-N의 Cluster Scope Operator 제약 설명 및 비오퍼레이터 헬름 또는 DKS-C 검토 합의) | 처리완료 |
| [15] | 2026051113491299093 | 2026-05-11 13:49:12 | 임유리 / DRAM YE팀 | 기타 | proxy-connect-timeout 상향 요청 (4분 타임아웃의 원인은 worker-shutdown-timeout 설정 이슈 확인 및 협의 종결) | 처리완료 |
| [16] | 2026051113313498841 | 2026-05-11 13:31:34 | 김정훈 / EDS 설비기술그룹 | 방화벽/네트워크 문의 | 방화벽 필요 확인 요청건 (호출 실패 405 에러 원인은 방화벽이 아닌 Ingress path 라우팅 미스매치 규명) | 처리완료 |
| [17] | 2026051110242496547 | 2026-05-11 10:24:24 | 장원호 / Platform Engineering그룹 | 기타 | C-DEP 의 DKS 클러스터 trident operator CPU 자원증설 요청 (ctzj, ctzs 클러스터 Trident Operator CPU Limit 무제한 변경 조치) | 처리완료 |
| [18] | 2026051110173596440 | 2026-05-11 10:17:35 | 조준현 / Foundry FAB운영혁신그룹 | 방화벽/네트워크 문의 | 가상 서버 접속 후 OS 방화벽 해제 관련 (클라우드 운영팀 지원으로 원격 접속 정상화 완료) | 처리완료 |
| [19] | 2026051109591596152 | 2026-05-11 09:59:15 | 고석준 / S/W Engineering팀 | 기타 | DKS project 사용자 추가요청드립니다 (One Cloud 프로젝트 멤버 추가 선행 절차 안내) | 처리완료 |
| [20] | 2026051108533795058 | 2026-05-11 08:53:37 | 장은비 / S/W Engineering팀 | 기타 | Node label 설정 (DKS-N 공용 노드 라벨 미지원 설명, 제어 대상 제외 임시 노드 지정 및 DKS-C 전환 권장) | 처리완료 |

---

## [1] DB Pod 접근 방법 문의

- **VOC 번호**: 2026051517142637735
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-15 17:14:26

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김선우(soular.kim)/S/W개발팀(메모리)**
> - Project명: Magician-AX
> - Cluster명: dks-magician-ax
> - Namespace명: mag-ax
> DB Pod 디버깅을 위해 외부 UI 툴에서 접근하고자 합니다. Ingress/Gateway가 80/443 중심이라 NodePort로 접근해야 하는지 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-15 18:07:08
> DKS-C 환경에서는 `type: LoadBalancer` 서비스를 생성하여 할당되는 External IP를 통해 TCP 통신이 가능합니다. 클러스터당 최대 3개의 LoadBalancer(기본 Ingress 1개 포함)를 지원하므로 사용자가 직접 2개까지 추가 구성하실 수 있습니다.

**김선우(soular.kim)/S/W개발팀(메모리)** · [게시됨] · 등록일: 2026-05-18 16:44:35
> LoadBalancer 타입으로 배포 후 방화벽(12.201.18.47:8200)을 오픈했으나 여전히 접근되지 않습니다. 확인 방법이 있을까요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-18 18:29:31
> 외부에서 LB까지의 방화벽은 정상 오픈되어 있으나, 서비스가 연결된 Pod(`192.7.1.205:8200`)로 직접 TCP 연결 테스트 시 `Connection Refused`가 발생합니다. 파드 내부 어플리케이션(PostgreSQL)의 Listen 포트 바인딩 및 파라미터 설정을 확인하시기 바랍니다.

---

## [2] 네임스페이스 이름변경 및 협력사 권한 문의

- **VOC 번호**: 2026051509123132269
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-05-15 09:12:32

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**황한동(hoasis.hwang)/비즈니스플랫폼1그룹(DS)**
> - Project명: 지원WP - Workplace Solutions
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: dsp-intra-dev
> 네임스페이스 이름을 `dsp-infra-dev`로 변경 요청드리며, 협력사 인력들에 대한 DKS 시스템 접근 권한 추가를 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-15 11:28:50
> 1. 쿠버네티스는 Namespace 이름 변경 기능을 지원하지 않습니다. 신규 네임스페이스 생성 후 워크로드를 이전하셔야 합니다.
> 2. 네임스페이스 멤버 권한은 One Cloud 포탈에서 해당 프로젝트의 멤버로 사용자를 먼저 추가하셔야 DKS에서 권한 할당이 가능합니다.

---

## [3] DKS 게이트웨이 배포 관련

- **VOC 번호**: 2026051417172629842
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-14 17:17:26

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김선우(soular.kim)/S/W개발팀(메모리)**
> - Project명: Magician-AX
> - Cluster명: dks-magician-ax
> - Namespace명: tanzu-system-ingress
> 1. 콘솔 UI에서 `tanzu-system-ingress` 네임스페이스가 보이지 않는 현상 문의
> 2. Gateway API 배포 시 TLS Secret 작성 yaml 예시 요청

**장(dsjj********)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-14 17:54:43
> 1. 시스템 네임스페이스는 기본적으로 UI에서 숨김 처리되어 있으며, 설정 메뉴에서 활성화하거나 kubectl CLI로 배포하시면 됩니다.
> 2. TLS Secret은 yaml base64 입력 방식 또는 `kubectl -n tanzu-system-ingress create secret tls public-cert --cert=./tls.crt --key=./tls.key` 명령으로 원본 파일 기반 생성이 가능합니다.

**김선우(soular.kim)/S/W개발팀(메모리)** · [게시됨] · 등록일: 2026-05-15 09:37:11
> 배포 완료 후 외부 OA망에서 접근 시 방화벽 URL 기반 신청이 막히는데 어떻게 해야 하나요?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-15 09:46:49
> 참조하신 가이드는 공용 DKS-N 가이드입니다. 현재 사용 중이신 DKS-C는 단독 클러스터 단위로 IP가 분리되어 제공되므로, 할당받으신 Ingress IP를 목적지(Destination)로 직접 방화벽 신청하시면 되며 URL Filtering 절차는 필요하지 않습니다.

---

## [4] dks내 namespace 신청안됨

- **VOC 번호**: 2026051414095927533
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-14 14:09:59

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**복병훈(b.bock)/Generative AI팀(AX/PI센터)**
> Project : spkg-cctv 에서 namespace 생성 시 '목록추가' 버튼을 눌러도 반응이 없습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-15 09:35:35
> 콘솔 기능 이상 조치 완료되어 현재 정상적으로 네임스페이스 신청이 가능합니다.

---

## [5] VKS 앱배포파이프라인 메뉴 버튼 권한 추가 가이드 요청

- **VOC 번호**: 2026051409462824287
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-14 09:46:28

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**전경민(kmin.jeon)/생산자동화IT그룹(AX/PI센터)**
> VKS 환경에서 특정 멤버들에게 '앱배포파이프라인' 메뉴 버튼이 보이지 않습니다. 권한 추가 방법을 문의드립니다.

**장(dsjj********)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-14 17:58:26
> 프로젝트 멤버 권한이 구성되지 않아 발생한 건으로, DKS 사용자 권한을 적용하여 정상 노출되도록 조치하였습니다.

---

## [6] DKS console(DKS2) Cluster 서비스의 Ingress IP 문의

- **VOC 번호**: 2026051317473421401
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-13 17:47:34

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**정연성(ys18.jeong)/Cloud Solution그룹(AX/PI센터)**
> - Project명: cae-cloud-monitoring
> - Cluster명: cae-pcloud-prod
> 클러스터 개요 화면에서 Ingress IP가 공란으로 표기되어 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-13 18:33:41
> 예정되어 있는 Control Plane 3중화 증설 작업 완료 후 정상화될 예정이며, 작업 이후 정상 조회가 가능합니다.

---

## [7] AI agent 서비스 웹 애플리케이션 형태의 배포 방식 문의

- **VOC 번호**: 2026051313272517851
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-13 13:27:25

### 대화 내용

**문석호(sh1994.moon)/품질AX/PI팀(메모리)**
> 품질분석 AI Agent 웹 애플리케이션 서비스 제공을 위한 VM 및 GPU 자원 배포 방식을 문의드립니다.

**윤혜진(hjin0.yun)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-05-13 16:26:58
> DS Cloud VM 및 Load Balancer를 통한 웹 서비스 운영 방식이 가능하며, GPU 자원은 일반 VM과 별도로 ASRB 가이드를 통해 신청하셔야 합니다. 연간 정기 수요조사(7월) 외 잔여자원 신청 절차를 안내드립니다.

---

## [8] 방화벽해제를위한 ip/port 문의

- **VOC 번호**: 2026051309014214595
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-05-13 09:01:42

### 대화 내용

**강재구(j9.kang)/해외파견(TSP총괄)**
> SESS 해외 법인에서 DSDN(`dsdn.samsungds.net`) 및 Assistant(`assistant.samsungds.net`) 접속을 위한 방화벽 IP/Port 정보를 문의드립니다.

**보안데스크16(security.sos16)/정보보호그룹(DS)** · [게시됨] · 등록일: 2026-05-13 10:50:15
> - `https://dsdn.samsungds.net`: IP `10.172.26.80` / TCP / 443
> - `https://assistant.samsungds.net`: IP `10.172.25.84` / TCP / 443

---

## [9] 육아 휴직 시 DKS 자원 및 권한 변경에 관한 문의 메일

- **VOC 번호**: 2026051216565011625
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-12 16:56:50

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**임승지(ted08.lim)/인프라AX/PI팀(글로벌 제조&인프라총괄)**
> 육아휴직 시 DKS 자원 관리 권한을 파트 내 타 인력으로 지정하면 서비스 유지에 문제가 없는지 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 17:34:02
> DKS 콘솔의 권한 관리 메뉴에서 대표관리자 및 관리자 권한을 위임하시면 기존과 동일한 권한으로 정상 운영 가능합니다.

---

## [10] Node별 ip 대역 문의

- **VOC 번호**: 2026051216363611350
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-12 16:36:36

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**박소연(sy1225.park)/S/W Engineering팀(AX/PI센터)**
> - Project명: DS-CodeReviewBot
> - Cluster명: prod-ds-member
> - Namespace명: crb-prd
> 사내 제어 대상 대역 외 노드 식별을 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 17:23:45
> 현재 prod-ds-member 클러스터에서 제어 대상 IP 외 노드는 `khdkswkmpdta01`, `khdkswkmpdta02`, `khdkswkmpdta03` 3대입니다. 임시로 해당 노드를 지정하여 배포하시거나, 12.x 대역을 단독 사용하는 DKS-C(클러스터 단위 서비스) Beta 도입을 권장드립니다.

---

## [11] 1.33 cluster kube config 설정 문의

- **VOC 번호**: 2026051215080609968
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-12 15:08:06

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**곽진철(jc.gwak)/PLM기술그룹(디지털PLM)**
> 클러스터 `prd-dksc-ic01-khm` (v1.33.3)을 P-DEP에 등록하고자 ServiceAccount Token 기반 Kubeconfig를 작성했으나 APISIX API Server에서 401 Unauthorized 에러가 발생합니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 15:57:42
> 해당 클러스터의 실제 소유자 정보 및 인증 연동 절차 확인이 필요하여 메신저를 통해 개별 가이드 지원 진행하였습니다.

---

## [12] DKS2 Baseimage 가져오는 방법 가이드 요청

- **VOC 번호**: 2026051210223006354
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-05-12 10:22:30

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**전경민(kmin.jeon)/생산자동화IT그룹(AX/PI센터)**
> DKS2 환경 CI/CD 빌드 시 Dockerfile에서 자체 Harbor 또는 DKS 레지스트리 Harbor로부터 Baseimage를 가져오는 방법을 문의드립니다.

**최(dshc********)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 13:25:05
> 외부 자체 Harbor 직접 조회는 지원되지 않으며, DKS 레지스트리 Harbor(`harbor.dks.samsungds.net`)에 이미지를 push한 후 사용하셔야 합니다.
> `latest` 기본 태그가 없는 경우 not found 오류가 발생하므로 Dockerfile의 FROM 절에 반드시 구체적인 이미지 태그(`FROM harbor.dks.samsungds.net/...:<tag>`)를 명시하시기 바랍니다.

---

## [13] 장애 원인 분석을 위한 호스트/CSI 로그 공유 요청

- **VOC 번호**: 2026051116153401388
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-05-11 16:15:34

### 대화 내용

> *(이관/중계성 안내 메시지 3건 제거)*

**고석준(seokjun.ko)/S/W Engineering팀(AX/PI센터)**
> - Project명: llm-gateway
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: llm-gateway-prod
> postgres pod 비정상 종료 및 재기동에 따른 데이터 유실 관련하여 노드/CSI(Trident)/스토리지 로그 확인을 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 16:07:22
> 노드 레벨 확인 결과 PostgreSQL 내부 프로세스에서 Signal 6(ABRT) coredump 및 CrashLoopBackOff가 발생한 것으로 확인되어 컨테이너 내부 애플리케이션 및 리소스 부족 점검을 안내드립니다.

**고석준(seokjun.ko)/S/W Engineering팀(AX/PI센터)** · [게시됨] · 등록일: 2026-05-13 11:06:34
> 5월 8일 23:00~24:00 시점 NetApp NAS 스토리지 이상 여부 확인 요청드립니다.

**DS Cloud Storage(dscstg.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-05-15 09:02:55
> NetApp 스토리지 장비 점검 결과 해당 시간대 aggregate 및 volume 상의 장애 이벤트 및 시스템 이상 로그는 전혀 없었음을 확인하였습니다.

---

## [14] Minio 헬름 차트 추가 요청

- **VOC 번호**: 2026051115122000391
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-11 15:12:20

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**조희원(hw0415.jo)/AX/PI팀(TSP총괄)**
> Minio Operator 헬름 차트 추가 및 CRD 생성 지원 여부를 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-11 16:38:08
> 기존 DKS-N(공용 네임스페이스) 서비스에서는 Cluster Scope 권한이 필요한 Operator 생성을 지원하지 않습니다. Operator가 없는 독립형 Helm을 사용하시거나, 클러스터 단위 권한이 부여되는 DKS-C Beta 서비스 이용을 검토하시기 바랍니다.

---

## [15] proxy-connect-timeout 상향 요청

- **VOC 번호**: 2026051113491299093
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-11 13:49:12

### 대화 내용

> *(이관/중계성 안내 메시지 3건 제거)*

**임유리(yoolee.lim)/DRAM YE팀(글로벌 제조&인프라총괄)**
> C-DEP 배포 서비스에서 4분 텀으로 세션이 끊겨 Ingress의 proxy-connect-timeout 30분 상향을 요청드립니다.

**남현종(hjong99.nam)/PLM기술그룹(디지털PLM)** · [게시됨] · 등록일: 2026-05-11 16:34:24
> 4분 타임아웃은 Ingress-controller의 `worker-shutdown-timeout`에 의해 발생하는 것으로 `proxy-connect-timeout`과는 무관한 현상입니다. 사용자 협의 후 처리 완료하였습니다.

---

## [16] 방화벽 필요 확인 요청건

- **VOC 번호**: 2026051113313498841
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-05-11 13:31:34

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김정훈(jh881229.kim)/EDS 설비기술그룹(글로벌 제조&인프라총괄)**
> DKS Service URL로 Batch API 호출 시 405 Method Not Allowed 에러가 발생하여 방화벽 문제인지 문의드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-11 14:48:33
> 405 응답은 방화벽 문제가 아니며, 백엔드로 전달되어야 할 요청이 Ingress 경로 매핑 미비로 인해 프론트엔드로 유입되어 발생한 현상입니다. Ingress backend path에 `/batch` 매핑을 추가하시기 바랍니다.

---

## [17] C-DEP 의 DKS 클러스터(prd-ctzs-pb01-khs, prd-ctzj-pb01-khs) trident operator CPU 자원증설 요청

- **VOC 번호**: 2026051110242496547
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-11 10:24:24

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**장원호(wannaon.jang)/Platform Engineering그룹(AX/PI센터)**
> C-DEP 클러스터의 Trident Operator CPU 사용률이 100%에 도달하여 PVC 생성 펜딩이 발생하므로 Limit 증설을 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-12 15:17:53
> `prd-ctzs-pb01-khs` 및 `prd-ctzj-pb01-khs` 클러스터의 Trident Operator CPU Limit을 무제한으로 변경 완료하였습니다.

---

## [18] 가상 서버 접속 후 OS 방화벽 해제를 하려고하나 가상서버 접속에 원격/ 콘솔로도 접속이 안되는 상황입니다. 확인 부탁드립니다.

- **VOC 번호**: 2026051110173596440
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-05-11 10:17:35

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**조준현(jhyun.cho)/Foundry FAB운영혁신그룹(글로벌 제조&인프라총괄)**
> Windows 서버 방화벽 설정 후 콘솔 및 원격 접속이 불가한 현상에 대해 조치를 요청드립니다.

**DS Cloud Guest OS(dscgos.sec)/Cloud Platform그룹(AI센터)** · [게시됨] · 등록일: 2026-05-11 10:59:51
> 사용자 유선 연락 후 원격 접속 정상화를 완료하였습니다.

---

## [19] DKS projet 사용자 추가요청드립니다.

- **VOC 번호**: 2026051109591596152
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-11 09:59:15

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**고석준(seokjun.ko)/S/W Engineering팀(AX/PI센터)**
> llm-gateway 프로젝트에 사용자 추가 및 admin 권한 부여를 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-11 10:51:20
> One Cloud 포탈에서 프로젝트 멤버 참여 신청/승인 후 DKS에 자동 동기화됩니다.

---

## [20] Node label 설정

- **VOC 번호**: 2026051108533795058
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-05-11 08:53:37

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**장은비(eb2994.jang)/S/W Engineering팀(AX/PI센터)**
> IP 대역 기반 노드 라벨 설정을 요청드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-05-11 11:29:24
> 공용 DKS-N 서비스의 노드는 공유 자원으로 사용자 라벨 관리를 지원하지 않습니다. 제어 대상 대역 외 노드 3대(`khdkswkmpdta01~03`)를 임시 지정하시거나 독립 12.x 대역을 사용하는 DKS-C 전환을 권장드립니다.
