# VOC 목록 — DS Cloud / 가상 자원(Container)-DKS (2026-03-15 ~ 2026-03-21)

- **수집 기간**: 2026-03-15 ~ 2026-03-21
- **시스템/세부시스템**: DS Cloud > 가상 자원(Container)-DKS
- **전체 건수**: **12건**

---

## 요약 목록

| 번호 | VOC 번호 | 등록일시 | 문의자 / 부서 | 문의 유형 | 제목 / 핵심 내용 | 상태 |
|:---:|:---:|:---:|:---|:---:|:---|:---:|
| [1] | 2026032015455775887 | 2026-03-20 15:45:57 | 소재우 / Generative AI팀 | 사용법 문의 | DKS 에서 NodePort 노출시 외부에서 접속하는 방법 문의 (Worker Node 1,2,3 IP 대상 방화벽 오픈 가이드) | 처리완료 |
| [2] | 2026032015044075665 | 2026-03-20 15:04:40 | 차문기 / 비즈니스플랫폼1그룹 | 장애/오류 접수 | DKS POD Pending 문제 (구버전 ReplicaSet 혼선 및 imagePullSecrets 403 인증 만료 갱신 조치) | 처리완료 |
| [3] | 2026032014335075503 | 2026-03-20 14:33:50 | 김신건 / S/W Culture사무국 | 방화벽/네트워크 문의 | DKS Knox API 활용 시 클러스터/노드 IP 기재 방법 문의 (클러스터별 Worker Node IP 대역 Source 방화벽 신청 안내) | 처리완료 |
| [4] | 2026032013191774953 | 2026-03-20 13:19:17 | 소재우 / Generative AI팀 | 인증서 문의 | Harbor 에 Push 가 안됩니다. 인증 문제 문의 (docker daemon insecure-registries 옵션 적용 가이드) | 처리완료 |
| [5] | 2026031916294570686 | 2026-03-19 16:29:45 | 권민수 / Foundry IMP기술팀 | 수요/자원 문의 | 신청가능 자원 오류 관련 문의 (변경신청 중단 현상 상세 확인 요청) | 처리완료 |
| [6] | 2026031814565059775 | 2026-03-18 14:56:50 | 윤승현 / 설비/인프라IT그룹 | 방화벽/네트워크 문의 | 특정 포트의 https통신 (11443 포트 인입 트래픽의 443 리다이렉트 DKS Ingress 기준 지원 불가 안내) | 처리완료 |
| [7] | 2026031811314757475 | 2026-03-18 11:31:47 | 최지영 / 생산자동화IT그룹 | 사용법 문의 | 해외법인 사용자 DKS 방화벽 신청 문의 (해외법인 FQDN 불가 시 Cluster VIP 목적지 방화벽 오픈 및 URL Filtering 안내) | 처리완료 |
| [8] | 2026031713412948754 | 2026-03-17 13:41:29 | 안도원 / 생산자동화IT그룹 | 수요/자원 문의 | 저활용리스트 측정 기준 문의 (일 평균 사용률 기반 기간 내 최고치 기준 판정 정책 및 회수 메일 안내) | 처리완료 |
| [9] | 2026031706472243959 | 2026-03-17 06:47:22 | 고중세 / Foundry Photo기술팀 | 수요/자원 문의 | DKS 자원 변경 신청 건 적용 도움요청드립니다 (PVC 삭제 미반영으로 인한 처리 중단 확인 및 재신청 가이드) | 처리완료 |
| [10] | 2026031618060242650 | 2026-03-16 18:06:02 | 변준혁 / 인프라/Workplace IT그룹 | 방화벽/네트워크 문의 | K8S 앱 DNS 등록 관련 IP 문의 (콘솔 표기 내부 IP 대신 nslookup 조회되는 Cluster VIP 등록 안내) | 처리완료 |
| [11] | 2026031615022639988 | 2026-03-16 15:02:26 | 김진철 / AX전략그룹 | 수요/자원 문의 | PowerFlex Storage Class 증설 요청 (스토리지 감설 불가 안내 및 산정 근거 첨부 변경신청 가이드) | 처리완료 |
| [12] | 2026031609361135305 | 2026-03-16 09:36:11 | 유용우 / Solution개발팀 | 기타 | Namespace 이름 변경 문의 (K8s 특성상 NS 이름 변경 불가, 기존 삭제 및 신규 생성 안내) | 처리완료 |

---

## [1] DKS 에서 NodePort 노출시 외부에서 접속하는 방법 문의

- **VOC 번호**: 2026032015455775887
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-20 15:45:57

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**소재우(jaewoo8.so)/Generative AI팀(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: RAG
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: vipreport-dev
> 테스트 pod로 외부에서 접속 테스트 중입니다. nodeport 로 노출시켰는데 접속이 안됩니다.
> 외부 접속을 위해서는 따로 해야하는 것들이 있나요?
> 아래는 일부 결과 입니다.
> ```yaml
> [dev-apps-pb01-khs:agentic-rag-dev] $ cat > hello-svc.yaml <<'EOF'
> apiVersion: v1
> kind: Service
> metadata:
>   name: hello-world-svc
>   namespace: agentic-rag-dev
> spec:
>   type: NodePort
>   selector:
>     app: hello-world
>   ports:
>   - port: 80
>     targetPort: 80
> EOF
> [dev-apps-pb01-khs:agentic-rag-dev] $ kubectl apply -f hello-svc.yaml
> service/hello-world-svc created
> [dev-apps-pb01-khs:agentic-rag-dev] $ kubectl -n agentic-rag-dev get svc hello-world-svc
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> hello-world-svc NodePort 10.224.211.195 <none> 80:31862/TCP 2s
> ```
> `kubectl get nodes -o wide` 실행 시 클러스터 권한 부족 에러 발생.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-23 11:38:27
> 안녕하세요 DKS 운영팀입니다.
> 외부 시스템에서 DKS 노드로의 접근을 위해서는 별도의 방화벽 신청이 필요합니다.
> 아래 가이드 참고하여 방화벽 진행 부탁드립니다.
> 외부 시스템 -> DKS Pod로의 통신이 필요합니다 (NodePort)
> 
> [방화벽 신청 정보 가이드]
> 1. Source: 접속 시스템
> 2. Destination: 대상 클러스터의 Worker Node 1,2,3의 IP
> 3. Port: 사용중인 NodePort
> 4. Protocol: TCP
> 
> 파드가 다른 워커 노드에 배포되어 있더라도 위 대표 IP를 통해 유입된 요청은 Service를 통해 실제 파드로 정상 라우팅됩니다.
> 감사합니다.

**소재우(jaewoo8.so)/Generative AI팀(AX/PI센터)** · [게시됨] · 등록일: 2026-03-26 17:00:29
> 안녕하세요.
> prod로 새로 할당 받아서 시도했는데 여전히 접속이 안됩니다.
> Worker-01 > 10.172.34.200
> Worker-02 > 10.172.102.44
> Worker-03 > 10.172.102.29
> 이 3개에 포트 30578로 접속해봤고, 연결 자체가 안됩니다.

**김(dsmk********)/Cloud Solution그룹(AI센터) (dsmk32791.id)** · [게시됨] · 등록일: 2026-03-27 09:16:18
> 안녕하세요. DKS 운영팀입니다.
> 먼저 해당 파드들에 대해서 직전에 안내드렸던 방화벽 오픈 신청에 대한 사항은 진행이 완료되었는지 확인 부탁드립니다.
> 방화벽 Open 은 어떻게 하나요? - DS Wikipedia - DS Confluence
> 오픈이 완료되었는지 여부가 확인되어야 추가 대응이 가능할 것으로 보입니다.
> 감사합니다.

---

## [2] DKS POD Pending 문제

- **VOC 번호**: 2026032015044075665
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 장애/오류 접수
- **등록일**: 2026-03-20 15:04:40

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**차문기(dsmc09393.id)/비즈니스플랫폼1그룹(DS)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: Digital-HR-Platform
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: perform-prd-prod
> 안녕하세요. 저희가 배포를 진행 중에 아래 캡쳐 처럼 Pod가 올라오다가 Pending 상태로 진행이 되지 않고 있어 문의 드립니다.
> - 이벤트 상으로는 Error: ImagePullBackOff 라고 나오는데 해당 이미지는 생성이 완료 된걸로 확인이 됩니다.
> - 그래서 해당 pod를 삭제 하려 시도 했지만 삭제도 되지 않고 있으며 Evict Pod를 이용해서 삭제도 되지 않고 있습니다.
> 어떻게 조치를 해야 할지 모르겠어서 확인 요청 드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-23 10:41:08
> 안녕하세요. DKS 운영팀 입니다.
> 최신 이미지(0320)가 아닌 이미 삭제된 과거 이미지(0121)를 가져오려다 실패하는 상황으로 확인되었습니다.
> 현재 perform-prd-prod Namespace 내에 두 개의 ReplicaSet이 존재합니다.
> 최신 버전을 바라보는 dshr--theuniverse-backend-prod-558c4759d8 리소스는 동작하지 않고(Desired 0),
> 과거 버전을 바라보는 dshr--theuniverse-backend-prod-6f88d548cb 리소스가 파드 생성을 계속 시도(Desired 2)하고 있어 정상적으로 완료되지 않고 꼬여있는 상태입니다.
> 
> [조치 가이드]
> 구버전 ReplicaSet의 복제본 수를 0으로 강제 조정:
> `kubectl scale rs dshr--theuniverse-backend-prod-6f88d548cb --replicas=0 -n perform-prd-prod`
> 조치 후 Deployment가 최신 0320 버전의 이미지를 정상적으로 배포하는지 확인부탁드립니다.
> 감사합니다.

**차문기(dsmc09393.id)/비즈니스플랫폼1그룹(DS)** · [게시됨] · 등록일: 2026-03-23 14:53:01
> 안녕하세요. 전달해 주신 내용 확인 하였습니다.
> 추가로 궁금한 사항이 있습니다. 수정 요청 하신 가이드가 Scale을 1로 줄여서 상황을 봐도 되는건지 아니면 무조건 0으로 조정을 해야 하는 것인지 궁금합니다.
> 현재 해당 POD의 경우 운영 중인 서비스로 POD의 스케일을 줄이게 되면 현재 서비스에 안 될 수도 있을 것 같아서 문의를 드렸습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-23 15:13:40
> 운영 중인 서비스의 가용성 확보가 필요하신 경우 말씀하신 대로 구버전 ReplicaSet을 1로 줄이고 신버전을 1로 늘려 상황을 확인하신 후
> 신규 파드가 생성되면 트래픽이 처리되는지 확인하고 이후 조정 진행하시면 됩니다.

**차문기(dsmc09393.id)/비즈니스플랫폼1그룹(DS)** · [게시됨] · 등록일: 2026-03-23 15:58:24
> 구 버전 ReplicaSet을 1로 줄이고 신버전을 2로 늘려서 진행을 하였습니다.
> Pod가 신규로 2개가 올라오면서 동일하게 Pending이 발생을 하였고 dshr--theuniverse-backend-prod-558c4759d8 신규 ReplicaSet을 읽으려고 시도하는데 이전과 동일하게 ImagePullBackOff가 발생하고 있습니다. 놓치는 부분이 있다면 가이드 부탁드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-23 16:53:28
> 해당 사항을 진행해도 동일하다면 파드에 설정된 imagePullSecrets 데이터가 인증 정보 변경 또는 정책적인 사유로 인해 달라지면서 imagePull이 실패하는 것으로 판단됩니다 (unexpected status from HEAD request 403 Forbidden).
> 아래 링크를 참조하시어 최신 Credential을 이용한 Secret 재발급 및 갱신 후 확인 부탁드립니다.
> Docker - App DevOps Guide - DS Confluence
> 감사합니다.

---

## [3] DKS Knox API 활용 시 클러스터/노드 IP 기재 방법 문의

- **VOC 번호**: 2026032014335075503
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-20 14:33:50

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**김신건(suerte.kim)/S/W Culture사무국(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 사전 작업 - DS Wikipedia - DS Confluence
> (DKS콘솔) Ingress 배포 - DS Wikipedia - DS Confluence
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: DS SW 지표 체계 구축
> - Cluster명: dev-apps-pb01-khs, dev-apps-pb01-khm
> - Namespace명: ai-security-dev, ai-security-prod
> 안녕하세요 DKS 내 App 에서 Knox API 활용하려고 합니다.
> Knox API 활용 시, 운영계의 경우에는 Source IP를 기재해야 하는데 아마 DKS 클러스터나 노드 IP 를 입력해야 할 것 같습니다. (Internal/External IP)
> 기재해야할 IP/대역 무엇인지 안내하여 주시면 감사하겠습니다.

**이(dsjl********)/Cloud Solution그룹(AI센터) (dsjl32783.id)** · [게시됨] · 등록일: 2026-03-20 15:14:22
> 안녕하세요 DKS 운영팀 입니다.
> DKS -> 외부 서버 일 경우 각 cluster 별 worker node ip대역을 source로 방화벽 해제가 필요합니다.
> DKS Pod -> 외부 시스템로의 통신이 필요합니다 - DS Wikipedia - DS Confluence
> 감사합니다.

---

## [4] Harbor 에 Push 가 안됩니다. 인증 문제인 것 같은데 가이드가 없어서 문의드립니다.

- **VOC 번호**: 2026032013191774953
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 인증서 문의
- **등록일**: 2026-03-20 13:19:17

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**소재우(jaewoo8.so)/Generative AI팀(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS 2-Tier 인증서 변경 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: RAG
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: vipreport-dev
> Harbor 에 Push 가 안됩니다. 인증 문제인 것 같은데 가이드가 없어서 문의드립니다.
> ```text
> docker push dcr.cloud.samsungds.net/dev-apps-pb01-khs_vipreport-dev/hello-world:latest
> The push refers to repository [dcr.cloud.samsungds.net/dev-apps-pb01-khs_vipreport-dev/hello-world]
> Get "https://dcr.cloud.samsungds.net/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
> ```

**이(dsjl********)/Cloud Solution그룹(AI센터) (dsjl32783.id)** · [게시됨] · 등록일: 2026-03-20 14:27:07
> 안녕하세요. DKS 운영팀 입니다.
> insecure registry 옵션을 적용하여 조치할 수 있습니다.
> 
> 1. `/etc/docker/daemon.json` 파일에 insecure-registries 옵션 추가:
> ```json
> {
>   "insecure-registries" : ["dcr.cloud.samsungds.net"]
> }
> ```
> 2. docker 데몬 서비스 재시작:
> `sudo systemctl restart docker`
> 3. `docker info`에서 Insecure Registry 옵션 정상 적용 확인 및 login 재시도
> `docker login dcr.cloud.samsungds.net`
> 
> 감사합니다.

---

## [5] 신청가능 자원 오류 관련 문의

- **VOC 번호**: 2026031916294570686
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-03-19 16:29:45

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**권민수(ms95.kweon)/Foundry IMP기술팀(글로벌 제조&인프라총괄)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: IMPtology
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: IMPtology
> 안녕하세요. 자원 변경 관련 문의로 연락드립니다. 신청가능 자원 관련 오류로 문의드립니다.
> 현재 활성화되어 있는 Namespace는 imptology-dks-dev (3cor/3Gi) , imptology-dks-prod(2Core/2Gi) 이지만,
> 신청 가능 자원 현황에 표기되는 자원량은 이미 개발에서는 11core/25Gi , 운영에서는 22cor/57Gi를 사용하고 있는 것 처럼 표기되어 자원 변경 신청에 장애가 있는 상태입니다.
> 혹시 조치 방법과 특이사항이 있다면 조언받을 수 있을까요 ?

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-20 17:31:35
> 안녕하세요. DKS 운영입니다.
> 자원 변경신청에 장애가 있다는게 어떠한 내용인지 확인 해 주실수 있을까요?
> 진행중 어떠한 문제가 발생하여 변경 신청을 하실 수 없는 상황이신지 설명이나 화면 첨부 주시면 도움이 될 것 같습니다.
> 감사합니다.

---

## [6] 특정 포트의 https통신

- **VOC 번호**: 2026031814565059775
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-18 14:56:50

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**윤승현(sh_ted.yun)/설비/인프라IT그룹(AX/PI센터)**
> 안녕하세요,
> 아래 구성으로 운영 중인 backend Pod통신이, api.memory.ssqs.samsungds.net 도메인을 통해 Cluster VIP(10.172.25.218)로 통신 중입니다. 443기본 https를 활용해 tls등록까지 해서 통신 중인데요,
> api.memory.ssqs.samsungds.net:11443이 443으로 redirecting되게끔 구성을 할 수 있을까요?
> 11443인 기존 서비스를 전환했는데, 메일에 하드코딩 된 링크가 있어서 client 측에서 443으로 URL변경이 안되는 상황이라 문의드립니다.
> Project : YMS-Batch-ETL
> Cluster : prd-apps-pb01-khm
> NameSpace : yms-batch-prod
> Pod : mem-ssqs--mem-ssqs-backend-prod
> svc : mem-ssqs--mem-ssqs-backend-prod-svc
> ingress : mem-ssqs--mem-ssqs-backend-prod-ing

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-18 16:42:29
> 안녕하세요. DKS 운영입니다.
> 확인 결과 문의주신 api.memory.ssqs.samsungds.net:11443 → 443(https) 리다이렉트 구성은
> DKS Ingress 기준으로는 지원이 어렵습니다.
> 감사합니다.

---

## [7] 해외법인 사용자 DKS 방화벽 신청 문의

- **VOC 번호**: 2026031811314757475
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 사용법 문의
- **등록일**: 2026-03-18 11:31:47

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**최지영(jy0620.choi)/생산자동화IT그룹(AX/PI센터)**
> 안녕하세요, 해외 법인(SCS, SAS) 사용자들에 대해서 DKS Pod 접속을 위해서는 방화벽 신청이 필요한데요.
> DKS에서는 개별 서비스 URL로 오픈을 진행하라고 하셔서 URL 기반(FQDN)으로 방화벽 신청을 했는데 해외 법인에서 FQDN 방화벽 신청이 불가하다고 답변을 받았습니다.
> 해외 법인 사용자들은 방화벽을 어떻게 신청해야하는지 가이드 부탁드립니다.
> - Project명: 표준SPEC-DKS
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: espec-prod

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-18 17:28:10
> 안녕하세요. DKS 운영팀 입니다.
> 해외 법인(SCS, SAS) 측에서 FQDN 기반 방화벽 신청이 불가한 경우에는, 해당 서비스가 매핑되는 클러스터 VIP(IP)를 목적지로 방화벽 오픈하시면 됩니다.
> 
> [VIP 확인 방법]
> cmd > nslookup {서비스 FQDN}
> 예) nslookup (app).khprdpb01.apps.dks.samsungds.net → 반환 IP(VIP)를 destination으로 신청
> (DKS콘솔) Ingress 배포
> 
> 또한, DKS는 기본적으로 URL 기반 방화벽 Open을 기본 정책으로 하고 있습니다. 가능한 경우 방화벽 open 시 필히 URL Filtering 절차까지 진행해주시기 바랍니다.
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 감사합니다.

---

## [8] 저활용리스트 측정 기준 문의

- **VOC 번호**: 2026031713412948754
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-03-17 13:41:29

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**안도원(dowon.ahn)/생산자동화IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: ui-airflow
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: ui-airflow-prod
> 안녕하세요. 생산자동화IT그룹 안도원입니다.
> 사용중인 네임스페이스가 저활용이라고 나오는데 실제 사용하는 양보다 적게 측정이 되는거 같은데 어떤 기준으로 측정되는지 문의드립니다.
> 그리고, 자원회수 예정이 되어 있을까요? 메일을 받지 못했는데 필요하다면 며칠까지 예외처리 필요한지 알려주시면 결재 진행하겠습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-17 14:19:54
> 안녕하세요 DKS 운영팀입니다.
> 대시보드와 별개로 저활용 판정 기준은 DKS에서 수집된 일 평균 사용률을 토대로 판정 기간 동안 최고 수치를 기준 삼아 판단합니다.
> 자세한 내용은 아래 링크를 참고해주시기 바랍니다.
> DKS 저활용 판정 기준 - DS Wikipedia - DS Confluence
> 자원회수 관련 내용은 이후 메일로 안내될 예정입니다.
> 감사합니다.

---

## [9] DKS 자원 변경 신청 건 적용 도움요청드립니다.

- **VOC 번호**: 2026031706472243959
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-03-17 06:47:22

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**고중세(joongse.ko)/Foundry Photo기술팀(글로벌 제조&인프라총괄)**
> - Project명: FDY-PHOTO-DX
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: photodx-prod
> 안녕하세요. 어제 DKS block storage -> nas storage 변경하는 내용의 변경 신청을 상신하여 결재 완료되었습니다.
> 그러나 아직 변경 적용이 안되었는데요. 제가 이전에 생성해 두었던 PVC를 뒤늦게 삭제하여 그럴 수 있을 것 같아 도움 요청드립니다.
> 지금은 PVC 삭제 해두었습니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-17 13:53:06
> 안녕하세요. DKS 운영팀 입니다.
> powerflexos-xfs-sc-300t-sp04 (Block) : requests.storage 0 / hard 10Gi
> netapp-economy-prd-nfs-sc-100t (NAS) : requests.storage 0 / hard 0
> 확인 결과, 현재 상태는 Block 할당(10Gi)은 유지되고 NAS 할당은 아직 반영되지 않은 상태로 보입니다.
> PVC 삭제 이슈로 반영이 불가한 상태라면 변경 신청을 재상신해주시기 바랍니다.
> 감사합니다.

**고중세(joongse.ko)/Foundry Photo기술팀(글로벌 제조&인프라총괄)** · [게시됨] · 등록일: 2026-03-17 13:58:35
> 반영이 불가한 상태라는게, 지금까지 반영이 안되었으면 해당 이슈 때문이니 재상신 필요하다는 말씀이신가요?
> 지금은 pvc 삭제 및 서비스 연결도 모두 해지한 상태입니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-17 14:38:17
> 네 현재처럼 기존 변경 신청이 계속 반영되지 않는다면 이슈로 기존 신청 건이 처리 흐름에서 중단된 상태일 가능성이 있어 재상신이 필요할 수 있습니다.

---

## [10] K8S 앱 DNS 등록 관련 IP 문의

- **VOC 번호**: 2026031618060242650
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 방화벽/네트워크 문의
- **등록일**: 2026-03-16 18:06:02

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**변준혁(junhyeok.byun)/인프라/Workplace IT그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 사전 작업 - DS Wikipedia - DS Confluence
> (DKS콘솔) Ingress 배포 - DS Wikipedia - DS Confluence
> GSAMS [방화벽 가이드] URL Filtering 신청 방법
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: OA AI Agent
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: dev-oa-ai-agent-dev
> k8s 로 띄운 service url 이 아닌 직접 지정한 url을 활용하기 위해서, DS 내부에 DNS 신청을하고 대상 ip 는 Network - Ingresses 에 로드밸런서 ip에 연결했습니다.
> 근데 정상적으로 통신이 되지 않아 확인해보니 기본적으로 주어지는 service url 은 nslookup 했을 때 해당 로드밸런서에 적혀있는 ip 가 아니라 다른 ip 로 통신을 하고 있음을 확인했습니다.
> - nslookup 했을때 조회되는 ip : 10.166.113.250
> - 로드 밸런서에 적혀있는 ip : 10.224.212.54
> svc url 과 연결되어 있는 ip 는 어디서 확인할 수 있을까요? 그리고 DNS 등록할 때 보통 위 IP 로 등록하는 것이 맞을까요?

**조(dsec********)/Cloud Solution그룹(AI센터) (dsec25527.id)** · [게시됨] · 등록일: 2026-03-17 11:02:31
> 안녕하세요 DKS 운영팀입니다.
> 확인 결과 Ingress "dev-oa-ai-agent--oa-ai-agent-k8s-dev-ing" 를 통해 아래 URL 등록되어 있습니다.
> `http://dev-oa-ai-agent--oa-ai-agent-k8s-dev.khdevpb01.apps.dks.samsungds.net/`
> 원하시는 DNS를 "10.166.113.250" 로 등록해주시고 DNS에 맞춰서 Ingress를 변경 해주시기 바랍니다.
> 
> [참고]
> "10.224.212.54" 는 Ingress 의 Cluster IP 로 클러스터 내부에서만 유효합니다.
> 감사합니다.

---

## [11] PowerFlex Storage Class 증설 요청

- **VOC 번호**: 2026031615022639988
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 수요/자원 문의
- **등록일**: 2026-03-16 15:02:26

### 대화 내용

> *(이관/중계성 안내 메시지 3건 제거)*

**김진철(jinpro95.kim)/AX전략그룹(AX/PI센터)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> 자원 신청하기 - DS Wikipedia - DS Confluence
> (DKS콘솔) 자원 변경 신청하기 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: aieval
> - Cluster명: dev-apps-pb01-khs
> - Namespace명: aieval-dev
> 안녕하세요. redis 추가 연동을 위하여 아래 StorageClass의 용량 증설이 필요합니다.
> powerflexos-xfs-sc-300t-sp04
> 증설 요청드립니다.
> 현재: 10GB -> 100GB

**서지희(jwlgmlz.seo)/Cloud Solution그룹(AX/PI센터)** · [게시됨] · 등록일: 2026-03-16 15:29:19
> 안녕하세요. Cloud Solution그룹 서지희입니다.
> 어떤 용량 산정 근거로 100GiB까지 필요한지 간략하게 내용 포함하여 Namespace 변경 신청 올려주시면 됩니다.
> 스토리지의 경우 용량 감설이 불가하기 때문에 꼭 필요한 만큼만 신청 부탁드립니다.
> 감사합니다.

---

## [12] Namespace 이름 변경 문의

- **VOC 번호**: 2026031609361135305
- **시스템 경로**: DS Cloud > 가상 자원(Container)-DKS > 공통 > 공통
- **상태**: 처리완료
- **문의 유형**: 기타
- **등록일**: 2026-03-16 09:36:11

### 대화 내용

> *(이관/중계성 안내 메시지 2건 제거)*

**유용우(yongwoo.yoo)/Solution개발팀(메모리)**
> DS Wikipedia를 통해 DKS 사용자 가이드를 제공하고 있습니다. 많은 이용 바랍니다.
> 가이드 링크 :
> DKS (DS Kubernetes Service) 가이드 - DS Wikipedia - DS Confluence
> 문의 내용에 Project명, Cluster명, Namespace명을 추가하여 작성해주시면
> 답변자가 더 신속하게 확인하여 답변 및 조치해드릴 수 있습니다.
> - Project명: canvas
> - Cluster명: prd-apps-pb01-khm
> - Namespace명: canvas-redis-prod
> 혹시 위의 namespace이름을 rabiitmq로 변경 가능할지 문의 드립니다.

**DKS 운영(dksmgmt.sec)/Cloud Solution그룹(AI센터)** · [게시됨] · 등록일: 2026-03-16 10:09:54
> 안녕하세요, DKS 운영팀입니다.
> 문의 주신 NS명 변경 관련하여 안내드립니다.
> 쿠버네티스에서는 기존 NS이름 변경 기능을 제공 하지 않습니다. 따라서 원하시는 NS명을 사용하시려면 현재 NS를 삭제 하신 후, 새로운 네임스페이스를 신청하셔야 합니다.
> NS 삭제 가이드는 아래 가이드를 참고 해주시기 바랍니다:
> (DKS 콘솔) 네임스페이스 삭제하기 - DS Wikipedia - DS Confluence
> 감사합니다.
